### PR TITLE
Updating pinned Scipy version

### PR DESCRIPTION
**Pull request by crazy4pi314**
Description
-----------
Addressing #839 and related install issues.

Checklist
-----------

Check off the following once complete (or if not applicable) after opening the PR. The PR will be reviewed once this checklist is complete and all tests are passing.

- [x] I added unit tests for new code.
- [x] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [x] I used [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings for functions.
- [x] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.

### CODE REVIEW

**Comment by andreamari** [comment]
@crazy4pi314 ,  this is not an important test and I would not consider it as a blocker.   I suggest the following options:

- Try replacing all the exponents `e9` in the variable `initial_guess` with something bigger `e10` or `e11`. 
- If the previous option doesn't work, you can mark it with the pytest option "skip" and I will think how to fix/replace this test without blocking this PR.

**Comment by crazy4pi314** [comment]
> * Try replacing all the exponents `e9` in the variable `initial_guess` with something bigger `e10` or `e11`.
I tried doing this but it didn't seem to help
> * If the previous option doesn't work, you can mark it with the pytest option "skip" and I will think how to fix/replace this test without blocking this PR.
Did this, it seems that `scipy.minimize` has slightly different behavior that is preventing it from failing like it did before.  Might be a change to a default method? Taking a quick look now..

**Comment by crazy4pi314** [comment]
Couldn't find a delta for the behavior for that function, we can troubleshoot this later then 👍

**Review by nathanshammah — APPROVED** [review]
LGTM, thank you @crazy4pi314.

**Pull request merged**
