### PR TITLE
remove gh-pages deploy action

### PR DESCRIPTION
**Pull request by natestemen**
## Description

We don't use the github pages website (https://unitaryfund.github.io/mitiq) and it has potential to be doubly indexed by search engines.

If this is merged, we should also delete the [`gh-pages`](https://github.com/unitaryfund/mitiq/tree/gh-pages) branch and deactivate the `gh-pages` "environment".

---

I was reminded about this by https://github.com/unitaryfund/mitiq/pull/1564.

### CODE REVIEW

**Review by Misty-W — APPROVED** [review]
Fine to delete this, the gh-pages workflow was created as a test.

**Comment by natestemen** [comment]
As a test for what?

I only found the history of this file through https://github.com/unitaryfund/mitiq/pull/1135 and https://github.com/unitaryfund/mitiq/pull/1243.

**Comment by Misty-W** [comment]
> As a test for what?
> 
> I only found the history of this file through #1135 and #1243.

I should've said it was an "experiment." Sarah was looking into using gh-pages as an alternative to read the docs but we didn't end up migrating.

**Comment by natestemen** [comment]
I guess it does allow for some added flexibility, but I don't think we have a use case for it yet. Easy enough to set back up if we decide to use it!

**Pull request merged**
