### PR TITLE
Remove qiskit-ibm-provider

### PR DESCRIPTION
**Pull request by andre-a-alves**
## Description

Removes `qiskit-ibm-provider`.

`qiskit-ibm-provider` is deprecated, and should be migrated to `qiskit-ibm-runtime` using the [migration guide](https://docs.quantum.ibm.com/api/migration-guides/qiskit-runtime-from-ibm-provider). The only use of `qiskit-ibm-provider` was in the docs, so this MR updates the docs to no longer use the deprecated module and drops the module from the mitiq[qiskit] requirements.

I let most of the examples send a circuit to IBM Quantum, and minor discrepancies in the code have been corrected from that as well.

This MR should also make dependabot MR #2306 unnecessary.

---

### License

- [X] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

Before opening the PR, please ensure you have completed the following where appropriate.

- [ ] I added unit tests for new code.
- [ ] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [ ] I used [Google-style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) docstrings for functions.
- [X] I [updated the documentation](../blob/main/docs/CONTRIBUTING_DOCS.md) where relevant.
- [ ] Added myself / the copyright holder to the AUTHORS file

### CODE REVIEW

**Comment by andre-a-alves** [comment]
I had to add the requirement for `qiskit-ibm-provider` back in for Pennylane on Python 3.9. A TODO is included to remove it when Pennylane gets upgraded.

**Review by cosenal — APPROVED** [review]
looks great!

**Comment by andre-a-alves** [comment]
After upgrading Pennylane, `qiskit-ibm-provider~=0.11.0` still needs to remain a requirement in `requirements-pennylane.txt` for Python 3.9 until `qiskit-ibm-runtime` is upgraded. The comment  was updated.

**Comment by cosenal** [comment]
Thanks for resolving the conflicts, @andre-a-alves, LGTM. Feel free to merge if you think it's ready to go.

**Pull request merged**
