### PR TITLE
Clean up contributing-to-docs doc

### PR DESCRIPTION
**Pull request by natestemen**
## Description

Went through some of this and cleaned up some wording/tried to make it more clear where I thought it wasn't.

**Question**: We seem to inconsistently use 80 character line breaks in some places and not in others. Not urgent, but would be nice to pick something and make it consistent.

### CODE REVIEW

**Comment by natestemen** [comment]
@Misty-W any idea why this is failing to build? I think it was first caused by the broken link, but the second failure seems to be something else entirely.

**Comment by andreamari** [comment]
I restarted the docs build on readthedocs. To see if it works. 
I also added the username `Misty-W` as admin on RTD. I hope it's you, @Misty-W  :-) 

I tried adding `natestamen` too, but the name doesn't exist. So, @natestemen, feel free create an account on RTD if you are interested in accessing RTD options.

**Review by Misty-W — APPROVED** [review]
LGTM!

**Comment by Misty-W** [comment]
💃🏼

**Pull request merged**
