### PR TITLE
Adds license.

### LINKED ISSUE #294: Add license to source files
I think we need to do this for the release right? @nathanshammah 

This is the template I found from https://www.gnu.org/licenses/gpl-3.0.en.html

```
<one line to give the program's name and a brief idea of what it does.>
Copyright (C) <year>  <name of author>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

### PR DESCRIPTION
**Pull request by rmlarose**
Fixes #294.

### CODE REVIEW

**Comment by rmlarose** [comment]
> * Shouldn't it start with "This file is part of Mitiq"?
> * Would replacing "2020" with "2020 and later" be helpful?
> * Out of curiosity, where did you find the template?
> * I found a place where it suggested to "<one line to give the program's name and a brief idea of what it does.>"
> * Should we add contact info, e.g., https://unitary.fund, [info@unitary.fund](mailto:info@unitary.fund)?

@nathanshammah the template is from https://www.gnu.org/licenses/gpl-3.0.en.html. I've always seen licenses at the very top of every file, so I stuck to that and put the docstring (one line description) below.

The rest are good questions that I don't know the answers to. I will merge this now and we can always update after.

**Comment by nathanshammah** [comment]
Great.

**Comment by nathanshammah** [comment]
Maybe we could add to the PR checklist to check that new file additions have copied the license.

**Comment by rmlarose** [comment]
> Maybe we could add to the PR checklist to check that new file additions have copied the license.

+1

**Pull request merged**
