### PR TITLE
Support python 3.12 and drop 3.9

### LINKED ISSUE #2395: Add Python 3.12 support
It looks like Cirq starting from [v1.4.0](https://github.com/quantumlib/Cirq/releases/tag/v1.4.0) and all other dependencies now support Python 3.12, so we are ready to add support for it in Mitiq as well.

### PR DESCRIPTION
**Pull request by natestemen**
## Description

Add support for python 3.12, **drop support for python 3.9**.

Fixes #2395
Fixes https://github.com/unitaryfund/mitiq/issues/2215

### CODE REVIEW

**Comment by natestemen** [comment]
Looks like this is hung up on Qibo now. They are working on supporting 3.12 on their end: https://github.com/qiboteam/qibojit/pull/170

**Comment by natestemen** [comment]
After rebasing and setting up the mitiq env with python 3.12, `make install` and `make test` were able to run with the current `cirq-core` restrictions (`cirq-core` 1.3.0 installed). We (@cosenal and I) previously thought that we would have to bump cirq-core in order for our tests to pass and hence merge the changes in https://github.com/unitaryfund/mitiq/pull/2390 into this PR, but this demonstrated not to be the case.

Hence, we are moving forward with "just" dropping python 3.9 and adding tested support for 3.12.

**Review by cosenal — APPROVED** [review]
LGTM 🚢🚢
When you merge it, please make sure the main commit message mentions dropping 3.9

**Comment by natestemen** [comment]
> make sure the main commit message mentions dropping 3.9

good idea. changed PR title to more accurately reflect that (and subsequently the merge commit).

**Pull request merged**
