### PR TITLE
Bump qiskit to version 0.31 and pin it explicitly in dev requirements

### PR DESCRIPTION
**Pull request by andreamari**
According to the discussion of the last Mitiq community call, this PR adds `qiskit`  in  `dev_requirements.txt`
and remove individual qiskit sub-packages to avoid conflicts.

Moreover it also updates `qiskit_utils.py ` for bumping Qiskit to the current latest version.

### CODE REVIEW

**Comment by andreamari** [comment]
I have no idea why the api-docs is failing but all tests are ok.

**Comment by andreamari** [comment]
@rmlarose, it would be good to have this for the new release. Tests are passing, the strange `-0.01%` of coverage can be ignored.

**Review by rmlarose — APPROVED** [review]

**Comment by rmlarose** [comment]
This test failed twice after merging to master:

https://github.com/unitaryfund/mitiq/blob/c577a60286b71973c85ba9c5358aca3c33ccb8f3/mitiq/zne/tests/test_zne.py#L378-L401

New changes maybe made it flaky, will keep an eye on.

**Comment by rmlarose** [comment]
Also seeing this (https://github.com/unitaryfund/mitiq/runs/4086436268?check_suite_focus=true#step:5:2344)

```text
=================================== FAILURES ===================================
_________________________ test_qiskit_execute_with_zne _________________________
[gw2] darwin -- Python 3.7.12 /Users/runner/hostedtoolcache/Python/3.7.12/x64/bin/python

    def test_qiskit_execute_with_zne():
        true_zne_value = 1.0
    
        circuit = qiskit_measure(
            *generate_rb_circuits(
                n_qubits=1,
                num_cliffords=TEST_DEPTH,
                trials=1,
                return_type="qiskit",
            ),
            0,
        )
        base = qiskit_executor(circuit)
        zne_value = execute_with_zne(circuit, qiskit_executor)
    
>       assert abs(true_zne_value - zne_value) < abs(true_zne_value - base)
E       assert 0.1600000000000006 < 0.15600000000000003
E        +  where 0.1600000000000006 = abs((1.0 - 1.1600000000000006))
E        +  and   0.15600000000000003 = abs((1.0 - 0.844))

mitiq/zne/tests/test_zne.py:300: AssertionError
```

**Pull request merged**
