### PR TITLE
Add linkcheck to docs build and fix broken links

### PR DESCRIPTION
**Pull request by rmlarose**
Description
-----------

This is a no-brainer to include to me. There were ~15 broken links in the docs.

Checklist
-----------

Check off the following once complete (or if not applicable) after opening the PR. The PR will be reviewed once this checklist is complete and all tests are passing.

- [x] I added unit tests for new code.
- [x] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [x] I used [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings for functions.
- [x] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.

If some items remain, you can mark this a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

Tips
----

- If the validation check fails:

    1. Run `make check-types` (from the root directory of the repository) and fix any [mypy](https://mypy.readthedocs.io/en/stable/) errors.

    2. Run `make check-style` and fix any [flake8](http://flake8.pycqa.org) errors.

    3. Run `make format` to format your code with the [black](https://black.readthedocs.io/en/stable/index.html) autoformatter.

  For more information, check the [Mitiq style guidelines](https://mitiq.readthedocs.io/en/stable/contributing.html#style-guidelines).
  
- Write "Fixes #XYZ" in the description if this PR fixes Issue #XYZ.

### CODE REVIEW

**Review by crazy4pi314 — APPROVED** [review]
Thanks for turning this on! I hate 💔🔗

**Comment by nathanshammah** [comment]
@rmlarose I like the tool. I don't agree on some of the changes: they redirect to the online html on RTD, while the previous syntax, e.g., `contributing.html`, made it general enough so that if one was on RTD, it would stay there, while if they were reading locally a built documentation, they would stay in the local tree. There must be a way to enable this. Maybe the problem is using `.html` at the end?

**Comment by nathanshammah** [comment]
Removing `html` in `contributing` does not work, neither with the proper suffix `contributing.myst` nor a random `contributing.rst`.  Ideas?

**Comment by rmlarose** [comment]
I'm sure relative links are possible. I didn't have time to look into it. PR welcome.

**Comment by crazy4pi314** [comment]
Docs are [here](https://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=linkcheck#options-for-the-linkcheck-builder), gonna see if I can fix this.

**Pull request merged**
