### PR TITLE
Improve naming of `noise_scaling_converter`

### LINKED ISSUE #1244: Improve naming and documentation of `noise_scaling_converter`
Pre-Request Checklist
---------------------

- [X] I checked to make sure that this feature has not already been requested.

Issue Description
-----------------

Give a detailed description of the new feature, and what problem it is trying to solve.

If this is a proposal to change an existing feature, also outline the current
implementation and its drawbacks.

Thanks for helping us improve Mitiq! 🙂

Proposed Solution
-----------------

The `noise_scaling_converter` function in `mitiq.interfaces` is actually more general than for noise scaling functions and its name should reflect that. Also, we should consider how to make it more prominent in the documentation, as it avoids the qubit naming issues observed in `convert_from_mitiq` for Qiskit circuits. 

Additional References
---------------------

If applicable, provide some references that will help us better understand the request.

### PR DESCRIPTION
**Pull request by MZuhairKhan**
## Description

Renamed all instances of `noise_scaling_converter` to `accept_qrogram_and_validate` since the validation is what sets this function apart from other ones in this file.

fixes #1244 

---

### License

- [x] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

Before opening the PR, please ensure you have completed the following where appropriate.
- [x] I added unit tests for new code.
- [x] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [x] I used [Google-style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) docstrings for functions.
- [x] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.
- [x] Added myself / the copyright holder to the AUTHORS file

### CODE REVIEW

**Comment by purva-thakre** [comment]
@MZuhairKhan `validate` is failing due to style issues. You can read more about how to correct them in [mitiq's docs](https://mitiq.readthedocs.io/en/stable/contributing.html#style-guidelines).

**Comment by MZuhairKhan** [comment]
> @MZuhairKhan `validate` is failing due to style issues. You can read more about how to correct them in [mitiq's docs](https://mitiq.readthedocs.io/en/stable/contributing.html#style-guidelines).

Thanks for the help @purva-thakre !

**Comment by Misty-W** [comment]
Thanks for the PR @MZuhairKhan ! I'd suggest the name not mention scaling, but instead the conversion,  which is the actual purpose of the function.

**Comment by MZuhairKhan** [comment]
@Misty-W Thanks for the tip. Any ideas on what to do with the tests?

**Comment by Misty-W** [comment]
> @Misty-W Thanks for the tip. Any ideas on what to do with the tests?

`test_converter(circuit_and_type)` should test more than just noise scaling functions, see 
https://github.com/unitaryfund/mitiq/blob/92162e1447eaadc225ddac12e63dc67888dd8b6e/mitiq/tests/test_conversions.py#L164

You could add a new test or parameterize the existing test.

**Comment by natestemen** [comment]
@MZuhairKhan nice work with this so far! Looks like Misty has given you some comments to help move this forward. Need anything further from our side?

**Comment by natestemen** [comment]
@MZuhairKhan if you can get this PR ready by June 20th, you'll still be in line to receive the unitaryHACK bounty. WDYT?

**Comment by MZuhairKhan** [comment]
@natestemen I am so sorry, I have not logged into github for the last few days. I was working on my thesis, so I was unable to make the changes Misty suggested. I will try to finish it this weekend.

**Pull request merged**
