### PR TITLE
[unitaryhack] Add thumbnails for examples

### LINKED ISSUE #1283: [unitaryhack-bounty] Add thumbnail images to documentation examples.
Issue Description
-----------------

Currently we have thumbnail images only for a fraction of the examples in the docs: https://mitiq.readthedocs.io/en/v0.15.0/examples/examples.html

It would be good to have thumbnail images for all examples.

Proposed Solution
-----------------

There are different ways of adding thumbnail images with sphinx gallery:

- Adding an hard-coded image, not necessarily plots produced by the associated example. 
- Using a self-generated plot produced by the example during the docs build.
- Adding an hard-coded image of a plot generated by the example. This may be useful for zooming or other image edits.

Any option is fine. What is important is having a final result that looks good and clear.

For an example a gallery that looks good see, e.g.,  https://pennylane.ai/qml/demonstrations.html

### PR DESCRIPTION
**Pull request by obliviateandsurrender**
Description
-----------

Added a folder called `_thumbnails` that contains the thumbnail images for the documentation example to be used in the sphinx gallery. All the images in this folder get copied to `_static` during the build. The thumbnails are a mix of hard-coded images of plots and self-generated images. 

Checklist
---------

- [X] Added myself / the copyright holder to the AUTHORS file

License
-------

- [x] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

-------
Fixes #1283.

### CODE REVIEW

**Review by natestemen — COMMENTED** [review]
This looks awesome, thanks for taking this on! Just a few questions/comments.

1. The thumbnail for one article (`examples/hamiltonians` in the conf.py file) was left unchanged. Could you change that into the same style as well?
2. The file `docs/source/_thumbnails/vqe-pyquil-demo.png` has a "clear" background while all the other pngs have a white background. Is there a reason to prefer one over the other? Can we make them consistent?

Great work!

---

Just for reference in case anyone else comes to look at this, this is now what the examples page looks like:
Screen Shot 2022-06-07 at 11 13 13 AM

**Comment by nathanshammah** [comment]
Looks awesome @obliviateandsurrender! Is this the xkcd plugin of matplotlib? Is there any trick we could learn about generating these thumbnails for the future? Could be the subject of another PR...

**Comment by nathanshammah** [comment]
@obliviateandsurrender the test issue seems to be that there is a ghost notebook left in the repo and not part of the index
```
/home/runner/work/mitiq/mitiq/docs/source/examples/Untitled.ipynb: WARNING: document isn't included in any toctree
```

**Comment by obliviateandsurrender** [comment]
Thanks for the review @natestemen! All of the points have been addressed now.
Thanks, @nathanshammah! Yes, this is the `xkcd` plugin of matplotlib. I think it makes graphs look more suitable for the thumbnails. You can simply call the graph generation code under `with plt.xkcd:` for this. For the future, I suggest including having a figure either from the graph or manually (via inkscape/illustrator/etc.) as part of the PR for the tutorial itself. 
Also, about the failing test - It was due Cirq shifting their QAOA example to another URL. I have added an updated link for the same.

**Review by nathanshammah — APPROVED** [review]
Looks awesome @obliviateandsurrender!

**Pull request merged**
