### PR TITLE
Patch 0.9.0

### LINKED ISSUE #736: non-dev Mitiq tries importing braket and fails
Pre-Report Checklist
--------------------

- [ x] I am running the latest version of mitiq
- [ x] I checked to make sure that this bug has not already been reported

Issue Description
-----------------
Non development installation should work without Braket but it fails.
I am not sure why but, by checking out older commits, the problem seems to happen after merging #706. 

How to Reproduce
----------------

### Code Snippet

```python
import mitiq
```

### Error Output
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrea/anaconda3/envs/test_release/lib/python3.9/site-packages/mitiq/__init__.py", line 19, in <module>
    from mitiq.collector import generate_collected_executor
  File "/home/andrea/anaconda3/envs/test_release/lib/python3.9/site-packages/mitiq/collector.py", line 26, in <module>
    from mitiq.interface import (
  File "/home/andrea/anaconda3/envs/test_release/lib/python3.9/site-packages/mitiq/interface/__init__.py", line 16, in <module>
    from mitiq.interface import (
  File "/home/andrea/anaconda3/envs/test_release/lib/python3.9/site-packages/mitiq/interface/mitiq_braket/__init__.py", line 16, in <module>
    from mitiq.interface.mitiq_braket.conversions import from_braket, to_braket
  File "/home/andrea/anaconda3/envs/test_release/lib/python3.9/site-packages/mitiq/interface/mitiq_braket/conversions.py", line 24, in <module>
    from braket.circuits import (
ModuleNotFoundError: No module named 'braket'
```

Environment Context
-------------------
New conda environment `pip install -e .` or `pip install -U mitiq `.

### LINKED ISSUE #737: mitiq.about() error without qiskit elements
Issue Description
-----------------
If Qiskit or Qiskit elements are not installed, `mitiq.about()` fails. 
Unlike #736, this problem is only localized in `mitiq.about()` seems an easy problem to fix. We probably need to assign default `"not installed"` values to some version variables.

How to Reproduce
----------------
### Code Snippet

```python
import mitiq
mitiq.about()
```

### Error Output

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrea/data/mitiq/mitiq/_about.py", line 73, in about
    Terra : {terra_version}
UnboundLocalError: local variable 'terra_version' referenced before assignment
```

### PR DESCRIPTION
**Pull request by rmlarose**
Description
-----------

Fixes #736 and fixes #737.

Checklist
-----------

Check off the following once complete (or if not applicable) after opening the PR. The PR will be reviewed once this checklist is complete and all tests are passing.

- [x] I added unit tests for new code.
- [x] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [x] I used [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings for functions.
- [x] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.

If some items remain, you can mark this a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

Tips
----

- If the validation check fails:

    1. Run `make check-style` (from the root directory of the repository) and fix any [flake8](http://flake8.pycqa.org) errors.

    2. Run `make format` to format your code with the [black](https://black.readthedocs.io/en/stable/index.html) autoformatter.

  For more information, check the [Mitiq style guidelines](https://mitiq.readthedocs.io/en/stable/contributing.html#style-guidelines).
  
- Write "Fixes #XYZ" in the description if this PR fixes Issue #XYZ.

### CODE REVIEW

**Review by andreamari — APPROVED** [review]
Thanks @rmlarose for the quick patch. LGTM

**Comment by andreamari** [comment]
Other things that we could do in this PR or in a different one:

- Add Braket in the output of `mitiq.about()`.
- in the file` mitiq/_typing.py`, I think we should replace: `from braket import Circuit as _BKCircuit` with `from braket.circuits import Circuit as _BKCircuit`.

**Review by nathanshammah — APPROVED** [review]
Great fixes, thanks @rmlarose! @andreamari's suggestions look fine to me (could also be added in another PR).

**Comment by andreamari** [comment]
@rmlarose  I added a couple of improvements. 
I tested new `mitiq.about()` in an environment with and without Braket and it seems to work as expected.
PTAL

**Pull request merged**
