### PR TITLE
update zne-4-low-level.myst

### PR DESCRIPTION
**Pull request by andreamari**
Suggested updates for the _What happens when I use ZNE?_ section (`zne-4-low-level.myst`) of the current zne-docs-reorg PR.

### CODE REVIEW

**Review by nathanshammah — APPROVED** [review]
Thanks @andreamari, it looks much better to me. One question: should `.Factory.extrapolate` be referenced as a method of the various model factories, e.g., `.RichardsonFactory.extrapolate`, `.MyFactory.extrapolate`etc.?

**Comment by nathanshammah** [comment]
The RTD automation seems to be building for too long.

**Comment by andreamari** [comment]
> The RTD automation seems to be building for too long.

Someone, maybe you :-), fixed the build: https://mitiq--1064.org.readthedocs.build/en/1064/

**Comment by nathanshammah** [comment]
I think I tried to restart it, but it was not clear what build it was targeting. I'll merge.

**Comment by andreamari** [comment]
> Thanks @andreamari, it looks much better to me. One question: should `.Factory.extrapolate` be referenced as a method of the various model factories, e.g., `.RichardsonFactory.extrapolate`, `.MyFactory.extrapolate`etc.?

Maybe yes, but I didn't want to select a specific subclass. Maybe `.BatchedFactory.extrapolate()` works better.

**Pull request merged**
