### PR TITLE
LRE build error

### PR DESCRIPTION
**Pull request by purva-thakre**
## Description

Test PR to check if the errors noticed by Nate persist for all builds. Tested the build locally without any issues. 

image

---

### License

- [ ] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

Before opening the PR, please ensure you have completed the following where appropriate.

- [ ] I added unit tests for new code.
- [ ] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [ ] I used [Google-style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) docstrings for functions.
- [ ] I [updated the documentation](../blob/main/docs/CONTRIBUTING_DOCS.md) where relevant.
- [ ] Added myself / the copyright holder to the AUTHORS file

### CODE REVIEW

**Comment by purva-thakre** [comment]
IDK what the issue is. RTD build fails right after I push a new commit.

**Comment by purva-thakre** [comment]
[SO](https://stackoverflow.com/questions/76883029/api-reference-building-locally-but-not-on-rtd) that might be possibly related to this issue. 

It's not clear why the build passes locally but fails with a `ModuleNotFoundError` on RTD.

**Comment by purva-thakre** [comment]
@natestemen I managed to get the import issues fixed by adding init files in the submodules. 
I am not too sure about what's preferred though. 

https://app.readthedocs.org/projects/mitiq/builds/25982251/

**Comment by cosenal** [comment]
> @natestemen I managed to get the import issues fixed by adding init files in the submodules. I am not too sure about what's preferred though because this deviates from what's followed in the submodules for other techniques.
> 
> https://app.readthedocs.org/projects/mitiq/builds/25982251/

Having init files in the submodules is a good practice.

**Pull request merged**
