### PR TITLE
Remove `make requirements`

### PR DESCRIPTION
**Pull request by purva-thakre**
## Description

As discussed in https://github.com/unitaryfund/mitiq/pull/2441#discussion_r1729258901

---

### License

- [ ] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

Before opening the PR, please ensure you have completed the following where appropriate.

- [ ] I added unit tests for new code.
- [ ] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [ ] I used [Google-style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) docstrings for functions.
- [ ] I [updated the documentation](../blob/main/docs/CONTRIBUTING_DOCS.md) where relevant.
- [ ] Added myself / the copyright holder to the AUTHORS file

### CODE REVIEW

**Review by natestemen — APPROVED** [review]
Surprised this isn't in the documentation! I guess that's part of the reason we aren't using it 😆.

Side note: the macos runners ran all the unit tests in <5 min! Not sure if they are getting faster, or if I've never noticed that before. Cool.

**Comment by purva-thakre** [comment]
> Surprised this isn't in the documentation! I guess that's part of the reason we aren't using it 😆

@natestemen You suggested we remove `requirements` from the docs build in a124cb0d1e5e11ee9b363dd752cef170bf85652c 🤣

**Comment by natestemen** [comment]
By "in the docs" I mean in the contributing documentation, rather than the build systems.

**Review by cosenal — APPROVED** [review]
thanks – good finding

**Pull request merged**
