### PR TITLE
Fixes bug with small stretches

### PR DESCRIPTION
**Pull request by rmlarose**
Fixes Issue #29.

Adds a check if `num_to_fold` is zero. 

Also changes behavior to round `num_to_fold` up or down instead of always rounding down to nearest integer.

### CODE REVIEW

**Comment by andreamari** [comment]
`num_to_fold = int(ngates * fractional_stretch / 2)`
Appears 3 times also in `folding_pyquil.py` (lines 31, 54, 128).  
Could you update those lines with the same rounding of `folding_cirq.py` ?

**Comment by rmlarose** [comment]
Woops, good catch. I made this a function so I don't make this mistake again. 

`round` returns an int when called with one argument. From the docs:

```
Docstring:
round(number[, ndigits]) -> number

Round a number to a given precision in decimal digits (default 0 digits).
This returns an int when called with one argument, otherwise the
same type as the number. ndigits may be negative.
Type:      builtin_function_or_method
```

**Comment by andreamari** [comment]
Thanks @rmlarose! From my side you can merge

**Comment by willzeng** [comment]
As this is reviewed and approved I'm going to merge it.

**Pull request merged**
