### PR TITLE
Uprade python support to 3.11

### PR DESCRIPTION
**Pull request by natestemen**
## Description

This PR builds Mitiq using python 3.11, as well as ensuring users know our latest, supported python range via the `python_requires` keyword in `setup.py`.

resolves https://github.com/unitaryfund/mitiq/issues/1560

### CODE REVIEW

**Comment by natestemen** [comment]
Looks like [`h5py`](https://github.com/h5py/h5py/) (which is a dependency of pyscf) does not yet support python 3.11, and hence this is blocked until they provide the requisite wheels. Issue is tracked here: https://github.com/h5py/h5py/issues/2146.

**Comment by natestemen** [comment]
Comment: the reason this PR was opened in January, and is not moving forward until now is that the RTD build was having problem, or taking extremely long. I originally planned to only move forward once everything was passing on python 3.11. However, I think it's best that we add testing for python 3.11 over ensuring the docs build with python 3.11. Hence I have removed that section of the PR, and will open a new issue to address RTD with 3.11.

**Review by andreamari — APPROVED** [review]
So, all CI tests pass with python 3.11 but we don't use python 3.11 for RTD, right? 
If so, sounds good and LGTM!

**Comment by natestemen** [comment]
> we don't use python 3.11 for RTD, right?

Yup, exactly! I've opened https://github.com/unitaryfund/mitiq/issues/1790 in case we want to down the line.

**Pull request merged**
