### PR TITLE
Refactor classical postprocessing in shadows module

### PR DESCRIPTION
**Pull request by natestemen**
## Description

PR to refactor [`mitiq/shadows/classical_postprocessing.py`](https://github.com/unitaryfund/mitiq/blob/e14a799a90665d12ea004e6342de0c39961a35dc/mitiq/shadows/classical_postprocessing.py).

Addresses some issues raised in #2129 

### Docs

Despite there being tests for the shadows module, as we saw in https://github.com/unitaryfund/mitiq/pull/2113/ the tests do not cover everything and a change can pass tests despite making drastic changes to the results in a tutorial.

| shadow tutorial before | after |
| ---------------------- | ----- |
| Screenshot 2024-01-10 at 4 21 03 PM | Screenshot 2024-01-10 at 4 19 44 PM | 

Note there is a _slight_ difference in the above plot. I'm not totally sure why.

| rshadow tutorial before | after |
| ----------------------- | ----- |
| Screenshot 2024-01-10 at 5 42 45 PM | Screenshot 2024-01-10 at 4 31 58 PM |

All the other plots that I checked look either identical, or very close.

### CODE REVIEW

**Comment by Misty-W** [comment]
@Min-Li, we noticed some slight differences in the plots after the re-factor. Is this a concern, or do you think the module is working fine?

**Comment by FarLab** [comment]
Hi Nate, I had a look at your PR today by going over the commits and it looks good to me! The only concern is the very small difference in the first plots you show, but that might be some randomness that is not fixed.

**Comment by natestemen** [comment]
> only concern is the very small difference in the first plots

Any idea where that change could be coming from? I have not been able to find it.

**Comment by FarLab** [comment]
> > only concern is the very small difference in the first plots
> 
> Any idea where that change could be coming from? I have not been able to find it.

looking at the shadows_tutorial notebook, the seed is fixed, and you didn't change that. So maybe that is not the cause.

**Review by FarLab — APPROVED** [review]
Looks good, not much to add besides the insignificant differences in the plot in the tutorial notebook.

**Comment by Min-Li** [comment]
> @Min-Li, we noticed some slight differences in the plots after the re-factor. Is this a concern, or do you think the module is working fine?

Looks good to me, since there are some changes in the code, for me, this slight change of the figure seems to result from adding/removing stages of random sampling (especially in the quantum measurement). But overall, I don't think there are any issues here.

**Pull request merged**
