### PR TITLE
Split requirements into core and development requirements

### LINKED ISSUE #475: Get install_requires in setup from requirements.txt
As noted in [setup.py](https://github.com/unitaryfund/mitiq/blob/master/setup.py#L36-L40), argument `install_requires` should be a subset of `requirements.txt`, but is defined independently. This should be pulled from [requirements.txt](https://github.com/unitaryfund/mitiq/blob/master/requirements.txt#L1-L3) to be more robust. (So that, e.g., if we need to bump the Cirq dependency, we only need to do it in one place.)

### PR DESCRIPTION
**Pull request by rmlarose**
Fixes #475.

### CODE REVIEW

**Comment by willzeng** [comment]
This looks good to me. I want to check with @nathanshammah though as I think we previous had split requirements that we then combined. @nathanshammah is there something we're missing about them being split? If you're good with it then it looks good to me.

**Review by nathanshammah — APPROVED** [review]
Thanks @rmlarose and @willzeng. The change looks fine to me. The dev requirements were removed in https://github.com/unitaryfund/mitiq/pull/258 by @karalekas, there were some comments in that discussion about the different rationale that one could use ([comment](https://github.com/unitaryfund/mitiq/pull/258#issuecomment-662734783) by @rmlarose); summarizing: `github` fork being used by developers actually making a PR or by "devs" that like to be on bleeding edge but will likely just use Mitiq as is, at first. I have no strong opinion, I am just ignorant on whether the names have any impact, especially w.r.t. PyPI, e.g., `dev_requirements.txt` or `development_requirements.txt`. I guess we can check with TestPyPI at release time.

**Review by karalekas — COMMENTED** [review]
I personally dislike the two requirements files, and I think it sort of goes against the spirit of `requirements.txt` for it to not actually include all the requirements to develop a repository, but ofc at the end of the day it's a convention. According to the Python packaging docs, the `install_requires` and `requirements.txt` are different things (read more about best practices [here](https://packaging.python.org/discussions/install-requires-vs-requirements/)). One thing that I've wanted to try that could alleviate this double definition (though it deviates somewhat from the best practices) is just to put `.` in the `requirements.txt`, which should install what is defined in `install_requires`.

**Comment by rmlarose** [comment]
I'll put this up for discussion at the Mitiq meeting for a final decision. I would favor a convention without multiply defined requirements - this just seems logical to me. A standard way I've seen this done is `requirements` and `dev_requirements` as done here.

If we want to really emphasize the distinction between `install_requires` and `requirements` as Peter notes, perhaps omitting `requirements` altogether and just defining them in `install_requires` is an option (keeping `dev_requirements`).

**Comment by rmlarose** [comment]
Decided to merge after Mitiq meeting, but since @karalekas wasn't there to voice his opinion I will leave time to allow for trial by combat or other refutations :-)

**Pull request merged**
