### PR TITLE
Make qiskit conversion more robust and update qiskit and scipy

### PR DESCRIPTION
**Pull request by ckissane**
Description
-----------
Updates qiskit and scipy to fix some issues with installing mitiq in some cases.
Makes the qiskit conversion more robust so it does not fail consistency tests done by qiskit in the newer version.

Checklist
-----------

Check off the following once complete (or if not applicable) after opening the PR. The PR will be reviewed once this checklist is complete and all tests are passing.

- [x] I added unit tests for new code.
- [x] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [x] I used [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings for functions.
- [x] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.

If some items remain, you can mark this a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

Tips
----

- If the validation check fails:

    1. Run `make check-style` (from the root directory of the repository) and fix any [flake8](http://flake8.pycqa.org) errors.

    2. Run `make format` to format your code with the [black](https://black.readthedocs.io/en/stable/index.html) autoformatter.

  For more information, check the [Mitiq style guidelines](https://mitiq.readthedocs.io/en/stable/contributing.html#style-guidelines).
  
- Write "Fixes #XYZ" in the description if this PR fixes Issue #XYZ.

### CODE REVIEW

**Comment by ckissane** [comment]
These tests don't fail locally

**Comment by rmlarose** [comment]
Can you describe what the new notebooks are? These seem separate from the PR title and description.

> Updates qiskit and scipy to fix some issues with installing mitiq in some cases.

Can you document what these issues are?

**Comment by ckissane** [comment]
@rmlarose Someone who is collaborating on the fork accidentally pushed those notebooks, that is now reverted.

**Comment by nathanshammah** [comment]
There is a very long error message on CI. https://github.com/unitaryfund/mitiq/pull/686/checks?check_run_id=2632667040

**Comment by crazy4pi314** [comment]
@ckissane is there anything you are blocked on that would help get this pull finished?

**Comment by ckissane** [comment]
> @ckissane is there anything you are blocked on that would help get this pull finished?

Oh sorry I thought this had already been merged, I believe it was blocked because the CI fails on your servers but not locally.

**Comment by crazy4pi314** [comment]
@ckissane ah gotcha. Could you update from master, and then I can try and diagnose why CI has errors and not locally.

**Comment by rmlarose** [comment]
Closing due to inactivity, please reopen as appropriate!

**Pull request closed without merging**
