### PR TITLE
Add a GitHub workflow for having Binder launch badges in PRs

### LINKED ISSUE #957: Binder launch badges for PRs
Pre-Request Checklist
---------------------

- [x] I checked to make sure that this feature has not already been requested.

Issue Description
-----------------

It would be really convient for reviewing PRs to have a premade mybinder link setup that could just be clicked on in the comments of the PR. 

Proposed Solution
-----------------

Binder has docs on how to do this with ready-to-copy GitHub actions: 

https://mybinder.readthedocs.io/en/latest/howto/gh-actions-badges.html

### PR DESCRIPTION
**Pull request by AkashNarayanan**
Description
-----------

This GitHub workflow will comment on a PR with a Binder launch badge which would facilitate reviewing of the PR.

Fixes #957

Checklist
-----------

Check off the following once complete (or if not applicable) after opening the PR. The PR will be reviewed once this checklist is complete and all tests are passing.

- [x] I added unit tests for new code.
- [x] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [x] I used [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings for functions.
- [x] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.

### CODE REVIEW

**Review by crazy4pi314 — COMMENTED** [review]
LGTM, I added others on the team for feedback/approval. Thanks!

**Review by rmlarose — APPROVED** [review]

**Comment by rmlarose** [comment]
Hey @AkashNarayanan this is failing in #971 ([log](https://github.com/unitaryfund/mitiq/pull/971/checks?check_run_id=3822515167)) - could you take a look?

<details>

```text
Run actions/github-script@v5
  with:
    github-token: ***
    script: var PR_HEAD_USERREPO = process.env.PR_HEAD_USERREPO;
  var PR_HEAD_REF = process.env.PR_HEAD_REF;
  github.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/${PR_HEAD_USERREPO}/${PR_HEAD_REF}) :point_left: Launch a binder notebook on branch _${PR_HEAD_USERREPO}/${PR_HEAD_REF}_`
  })
  
    debug: false
    user-agent: actions/github-script
    result-encoding: json
  env:
    PR_HEAD_REF: execute_with_keyword_only_args
    PR_HEAD_USERREPO: unitaryfund/mitiq
TypeError: Cannot read property 'createComment' of undefined
Error: Unhandled error: TypeError: Cannot read property 'createComment' of undefined
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4942:56), <anonymous>:5:15)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4943:12)
    at main (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4997:26)
    at Module.272 (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4981:1)
    at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:43:19)
    at /home/runner/work/_actions/actions/github-script/v5/dist/index.js:49:18
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:52:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```

</details>

**Comment by AkashNarayanan** [comment]
@rmlarose This could be because of a [change](https://github.com/actions/github-script#breaking-changes-in-v5) in version 5 of `github-script`.

> For example, `github.issues.createComment` in V4 becomes `github.rest.issues.createComment` in V5

Making this change should hopefully fix the problem. Sorry for not noticing it earlier. Should I open a PR with the change?

**Comment by rmlarose** [comment]
Thanks so much @AkashNarayanan, this is very helpful!!

**Comment by crazy4pi314** [comment]
@all-contributors add @AkashNarayanan for infra

**Pull request merged**
