### PR TITLE
prepare v0.21.0 release

### PR DESCRIPTION
**Pull request by Misty-W**
## Description

Update changelog and version for v0.21.0 release.

---

### License

- [X] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

Before opening the PR, please ensure you have completed the following where appropriate.
- [X] I added unit tests for new code.
- [X] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [X] I used [Google-style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) docstrings for functions.
- [X] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.
- [X] Added myself / the copyright holder to the AUTHORS file

### CODE REVIEW

**Comment by Misty-W** [comment]
hi @natestemen, can you review this PR? Hoping to address any comments and get it merged today to proceed with the release. 

Note: baseline is "no PEC tutorial". If Nathan approves Vincent's PR I will revert my last commit to this PR (deleting mention of the tutorial). Other than that this PR is stable AFIK.

**Review by natestemen — COMMENTED** [review]
Looks good. Can we add a comment about how identity insertion is now documented with a link to the docs?

**Comment by Misty-W** [comment]
> Looks good. Can we add a comment about how identity insertion is now documented with a link to the docs?

Good catch! I've added a line about the identity insertion docs in the summary.

**Review by natestemen — APPROVED** [review]
🚢

**Comment by Misty-W** [comment]
🎉

**Pull request merged**
