### PR TITLE
Fix problem of notebooks without output in Read the Docs

### LINKED ISSUE #573: Readthedocs fails to reproduce output cells of some myst notebooks
Read The Docs fails to execute some notebooks and just reproduces input cells without the output cells. 
Se e.g. https://mitiq.readthedocs.io/en/stable/examples/simple_landscape.html or https://mitiq.readthedocs.io/en/stable/examples/maxcut-demo.html.

It works locally, in my usual environment where `mitiq` is installed. It fails if I create a new conda environment.

The problem currently happens for `maxcut-demo.myst` and `simple_landscape.myst` and seems to be related to the
line `import mitiq`.

Indeed: 
   - `test.myst` works but
   - If I add `import mitiq` in a code cell of `test.myst`, then `make docs` fails.
   - If I execute `pip install -e .`, `make docs` works.

### Error output from local log files in docs/build/html/reports/ in a new conda environment

```
Traceback (most recent call last):
  File "/home/andrea/anaconda3/envs/py38/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/andrea/anaconda3/envs/py38/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/andrea/anaconda3/envs/py38/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/andrea/anaconda3/envs/py38/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/andrea/anaconda3/envs/py38/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/andrea/anaconda3/envs/py38/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/andrea/anaconda3/envs/py38/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/andrea/anaconda3/envs/py38/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import mitiq
import matplotlib.pyplot as plt
import numpy as np
data = np.random.rand(3, 100) * 100
data[:, :10]
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-32243266b653>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mimport[0m [0mmitiq[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mpyplot[0m [0;32mas[0m [0mplt[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mdata[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mrandom[0m[0;34m.[0m[0mrand[0m[0;34m([0m[0;36m3[0m[0;34m,[0m [0;36m100[0m[0;34m)[0m [0;34m*[0m [0;36m100[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mdata[0m[0;34m[[0m[0;34m:[0m[0;34m,[0m [0;34m:[0m[0;36m10[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'mitiq'
ModuleNotFoundError: No module named 'mitiq'
```

### Error output from Read The Docs:

```
WARNING: Execution Failed: /home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/stable/docs/source/examples/maxcut-demo.myst
WARNING: Execution Failed: /home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/stable/docs/source/examples/simple_landscape.myst
WARNING: Couldn't find cache key for notebook file examples/maxcut-demo.myst. Outputs will not be inserted.
  Last execution failed with traceback saved in /home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/stable/docs/source/_build/html/reports/maxcut-demo.log
WARNING: Notebook code has no file extension metadata, defaulting to `.txt`
WARNING: Couldn't find cache key for notebook file examples/simple_landscape.myst. Outputs will not be inserted.
  Last execution failed with traceback saved in /home/docs/checkouts/readthedocs.org/user_builds/mitiq/checkouts/stable/docs/source/_build/html/reports/simple_landscape.log
WARNING: Notebook code has no file extension metadata, defaulting to `.txt`
```

### Mitiq installation:
```
Mitiq: A Python toolkit for implementing error mitigation on quantum computers
==============================================================================
Authored by: Mitiq team, 2020 & later (https://github.com/unitaryfund/mitiq)

Mitiq Version:	0.6.0

Core Dependencies
-----------------
Cirq Version:	0.10.0.dev
NumPy Version:	1.20.1
SciPy Version:	1.4.1

Optional Dependencies
---------------------
PyQuil Version:	2.18.0
Qiskit Version:	0.16.4

Python Version:	3.9.1
Platform Info:	Linux (x86_64)
```

### PR DESCRIPTION
**Pull request by andreamari**
This is a possible way to fix #573 . 

Description
-----------

The current problem is that when read the docs executes a notebook, mitiq is not installed and the the root folder of the mitiq repo  is not visible from the notebook. 

This PR adds a `mitiq.py ` file in `docs/source/examples` which is fake wrap of the true `mitiq` module. In this way,
the instruction `import mitiq` in each notebook works properly during the building of the docs.

This trick was suggested here: https://mg.readthedocs.io/importing-local-python-modules-from-jupyter-notebooks/sys-path-in-helper-module/path-helper.html

@crazy4pi314, I see only now that you self-assigned #576 .  What do you think?

For a preview of the result: https://mitiq.readthedocs.io/en/try-fixing-notebooks/examples/simple_landscape.html

Checklist
-----------
Please make sure you have finished the following tasks before requesting a review of the pull request (PR). For more information, please refer to the [Contributor's Guide](../blob/master/CONTRIBUTING.md):

- [ ] Contributions to mitiq should follow the [pep8 style](https://www.python.org/dev/peps/pep-0008/). You can enforce it easily with [`black`](https://black.readthedocs.io/en/stable/index.html) style and with [`flake8`](http://flake8.pycqa.org) conventions.
- [ ] Please add tests to cover your changes, if applicable, and make sure that all new and existing tests pass locally.
- [ ] If the behavior of the code has changed or new feature has been added, please also [update the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md).
- [ ] Functions and classes have useful [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings and [type hints](https://www.python.org/dev/peps/pep-0484/) in the signature of the objects.
- [x] (Bug fix) The associated issue is referenced above using [auto-close keywords](https://help.github.com/en/articles/closing-issues-using-keywords). If the PR fixes an issue, use the keyword fix/fixes/fixed followed by the issue id. For example, if the PR fixes issue 1184, type "Fixes #1184" (without quotes).
- [x] The [changelog](https://github.com/unitaryfund/mitiq/blob/master/CHANGELOG.md) is updated, including author and PR number (@username, gh-xxx).

### CODE REVIEW

**Review by crazy4pi314 — APPROVED** [review]
Yeah this looks like a decent solution. I think when I was locally testing this I had Mitiq installed in the docker container as I built it (maybe?)

**Review by nathanshammah — COMMENTED** [review]
@andreamari thanks for the fix. How can one reproduce the issue of #573 locally? I am just surprised this is not taken care of by `myst` somehow, by tweaking only the `conf.py`.

**Comment by andreamari** [comment]
> @andreamari thanks for the fix. How can one reproduce the issue of #573 locally? I am just surprised this is not taken care of by `myst` somehow, by tweaking only the `conf.py`.

To reproduce the issue locally: 
1. create and activate a new conda environment with python 3.7. 
2. clone mitiq but don't install it in the new environment.
3. `make docs `should fail (errors are logged in `docs/build/html/reports`)
4. `pip install -e .`, p`ip install -r dev-requirements.txt`
5. `make docs` should work

See #573 for more info about the error output.

I agree that it would be much better if it were possible to just tweak the `conf.py` file.

**Comment by nathanshammah** [comment]
@andreamari  I wonder if this bit on the RTD documentation on the [build process](https://docs.readthedocs.io/en/stable/builds.html#understanding-what-s-going-on) can help us:

> The first step of the process is that we check out your code from the repository you have given us. If the code is already checked out, we update the copy to the branch that you have specified in your project’s configuration.
> 
> Then we build the proper backend code for the type of documentation you’ve selected, this is done inside a Docker container.
> 
> At this point, if you need extra requirements, or even install your own package in the virtual environment to build your documentation, you can use a Configuration File.
> 
> When we build your Sphinx documentation, we run sphinx-build -b <format> . _build/<format> We also create pdf’s and ePub’s automatically based on your project. For MkDocs, we run mkdocs build.
> 
> Once these files are built, they are deployed to our file hosting backend and will be visible to users.
> 
> An example in code:
> 
> update_docs_from_vcs(version)
> config = get_config(project)
> if config.python.install.method.pip:
>     run('pip install .')
> if config.python.install.requirement:
>     run('pip install -r %s' % config.python.install.requirement)
> build_docs(version)
> deploy_docs(version)
> 

But maybe the issue is just for notebooks, and this does not fix that as the issue is myst-related, i.e. having jupyter notebooks run by myst in an environment where mitiq is not installed at all, and still wouldn't even when a RTD config file is included.

**Comment by crazy4pi314** [comment]
I'll look and see if I can specify a docker container for the RTD execution, maybe that could be a better solution in the future.

**Comment by andreamari** [comment]
@nathanshammah @crazy4pi314, what about if merge this (perhaps sub-optimal) solution just to fix the bad rendering of our latest docs? 
We can still easily use alternative solutions in the future (one would just need to remove the file `examples/mitiq.py`).

**Comment by nathanshammah** [comment]
@andreamari agreed.

**Review by nathanshammah — APPROVED** [review]

**Pull request merged**
