### PR TITLE
Build documentation with Sphinx

### PR DESCRIPTION
**Pull request by nathanshammah**
Set up the documentation with sphinx. 

Under author(s), set up for now, "Tech Team @ Unitary Fund".

### CODE REVIEW

**Comment by nathanshammah** [comment]
I don't see the Github Action continuous integration tests. How do they work? I thought they would be triggered for any PR. Or are they run only on merge or after an approval?

**Comment by andreamari** [comment]
> I don't see the Github Action continuous integration tests. How do they work? I thought they would be triggered for any PR. Or are they run only on merge or after an approval?

Maybe the reason is that your PR is based on a Forked version of the repository and not a branch of it?  @willzeng probably knows about this

**Comment by willzeng** [comment]
Yes likely it's because it's from a fork. You can see the example at https://github.com/unitaryfund/mitiq/pull/48 which runs the CI on the PR

Let me know if you find a way for the actions to also run on PRs from forks. I bet this is just a config thing

**Comment by willzeng** [comment]
On review it looks like this behavior is intentional: 

https://github.community/t5/GitHub-Actions/Run-a-GitHub-action-on-pull-request-for-PR-opened-from-a-forked/td-p/15426

@nathanshammah can you please re-submit this PR from a branch on the main repo?

**Comment by willzeng** [comment]
Alternatively you could enable the GitHub actions on your fork

**Comment by willzeng** [comment]
@nathanshammah I'm still not seeing the tests on this one for some reason. Maybe you need to retrigger the build.

Also, on this branch it looks like the `/build` is also checked into source. In the past I've just checked the source intro version control and not the build that is generated. Is there a particular reason we should keep the autogenerated stuff in the .git repo?

**Comment by nathanshammah** [comment]
@willzeng you are right. I added `docs/build` to the gitignore. I also adedd a markdown file with some information on the recipe to make the docs as I always find it confusing on the Sphinx website.

**Comment by nathanshammah** [comment]
I cleaned the `/docs/build/` folder, as I think it will keep picking up the content unless this PR is merged, as it contains the updated `.gitignore`. 

I am happy for this to be reviewed. 

Some comments: 

## README for contributing to the documentation
I added a recipe on how to generate and contribute to the documentation in [`docs/README-docs.md`](https://github.com/unitaryfund/mitiq/blob/d53ef7e4b7cffbe19b03dce336f01efe95eee5a6/docs/README-docs.md), this is mainly a note to self, as the Sphinx documentation is a mess and every time I get a bit lost once again, but maybe it can be helpful also to you @andreamari @rmlarose @willzeng. My idea was to add there all the step-by-step instructions (to be improved) that could be followed especially when there is a new release and a new documentation needs to be built. 

Nice to see that builds are working on each PR new commit, and now also with Python 3.8. 

I think it is a first step to start, then as you will see in the [Mitiq-01.pdf](https://github.com/unitaryfund/mitiq/blob/d53ef7e4b7cffbe19b03dce336f01efe95eee5a6/docs/pdf/Mitiq-0.1.pdf) file, there is much to improve.

**Pull request merged**
