### PR TITLE
Depend only on cirq-core

### PR DESCRIPTION
**Pull request by rmlarose**
Description
-----------

Self-explanatory. We will get some warnings on `import cirq` because `cirq-google` is not installed. (Until v0.14, `cirq-core` will try to disguise `cirq-google` as `cirq.google` for backwards compatibility.)

Note that just `cirq~=0.11.0` leads to a [quite mysterious Sphinx error](https://github.com/unitaryfund/mitiq/runs/2568891794?check_suite_focus=true) which I believe is from cirq-core renaming `cirq_google` to `cirq.google`.

Checklist
-----------

Check off the following once complete (or if not applicable) after opening the PR. The PR will be reviewed once this checklist is complete and all tests are passing.

- [ ] I added unit tests for new code.
- [ ] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [ ] I used [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings for functions.
- [ ] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.

If some items remain, you can mark this a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

Tips
----

- If the validation check fails:

    1. Run `make check-style` (from the root directory of the repository) and fix any [flake8](http://flake8.pycqa.org) errors.

    2. Run `make format` to format your code with the [black](https://black.readthedocs.io/en/stable/index.html) autoformatter.

  For more information, check the [Mitiq style guidelines](https://mitiq.readthedocs.io/en/stable/contributing.html#style-guidelines).
  
- Write "Fixes #XYZ" in the description if this PR fixes Issue #XYZ.

### CODE REVIEW

**Comment by rmlarose** [comment]
I'm a little worried this keeps popping up:

```python
/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/pyquil/api/_compiler.py:480: UserWarning: Request to quilc at tcp://127.0.0.1:5555 timed out. This could mean that quilc is not running, is not reachable, or is responding slowly.. Compilation using quilc will not be available.
  warnings.warn(f"{e}. Compilation using quilc will not be available.")
```

Currently I don't know the root cause of this.

**Comment by crazy4pi314** [comment]
Can you verify the PyQuil docker image is still working? I know some of the tests require that to be spun up and then the tests ping that as the backend I think...

**Comment by rmlarose** [comment]
> Can you verify the PyQuil docker image is still working? I know some of the tests require that to be spun up and then the tests ping that as the backend I think...

Any pyQuil tests which run circuits indeed require this. How to check if its still working though (beyond seeing that the tests pass)?

**Review by andreamari — APPROVED** [review]
LGTM!  
About the Cirq warnings: 
does it mean that `import cirq` raises a warning while `from cirq import something` doesn't?
If so this is not a big problem for us, I guess.

**Comment by rmlarose** [comment]
> About the Cirq warnings:
> does it mean that `import cirq` raises a warning while `from cirq import something` doesn't?

I think so.

I will bring this up at Mitiq meeting before merging since I'm not sure how to address Sarah's comment. There's a few small points that will be good to bring up to everyone as well.

**Comment by rmlarose** [comment]
> I'm a little worried this keeps popping up:
> 
> ```python
> /opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/pyquil/api/_compiler.py:480: UserWarning: Request to quilc at tcp://127.0.0.1:5555 timed out. This could mean that quilc is not running, is not reachable, or is responding slowly.. Compilation using quilc will not be available.
>   warnings.warn(f"{e}. Compilation using quilc will not be available.")
> ```
> 
> Currently I don't know the root cause of this.

I've seen this same warning on [an unrelated PR](https://github.com/unitaryfund/mitiq/runs/2477545615?check_suite_focus=true#step:5:419), so I don't think this is related to the `cirq-core` change in any way. Perhaps it's due to a [recent quilc change](https://github.com/quil-lang/quilc/commit/45da5a018b4c8068f26cc683db813ea29d85445c).

**Pull request merged**
