### PR TITLE
RFC: Layerwise Richardson Extrapolation

### LINKED ISSUE #2224: RFC: Layerwise Richardson Extrapolation (LRE)
Link to the RFC: https://docs.google.com/document/d/1yAQI8K8ShGI4jdn8OtpBv-H0X5SvkFVXA7DKtVOqm-8/edit?usp=sharing

### PR DESCRIPTION
**Pull request by purva-thakre**
[Layerwise Richardson Extrapolation RFC](https://docs.google.com/document/d/1oFRl4wMGMtn57V0c_1egaHh0WUUAbtgW-U_QxNL9_kY/edit?usp=sharing)

Fixes #2224

### CODE REVIEW

**Comment by purva-thakre** [comment]
I'll be late to the Community call today due to another appointment right before. 

Apologies for the delay in adding this RFC! We can discuss the proposed changes async through the Google doc comments if there's not enough time during the community call.

**Comment by purva-thakre** [comment]
Andrea left a comment on the RFC that we should keep the LRE and ZNE inference methods separate. Initially, I thought it would be better to move `mitiq.zne.inference` to `mitiq.inference` in order to avoid defining another module for the multivariate extrapolation methods. 

The refactor to the `Factory` class in mitiq would have comprised of :`polyfit` works for single variable extrapolation and there would be another option for the multivariate extrapolation. Based on Andrea's comments, this refactor would be a major breaking change. 

https://docs.google.com/document/d/1oFRl4wMGMtn57V0c_1egaHh0WUUAbtgW-U_QxNL9_kY/edit?disco=AAABMa8k_iI

FWIW I do agree with Andrea that this would be a major breaking change. I thought of proposing this breaking change to make it possible for us to extend multivariate extrapolation beyond Richardson extrapolation (in the near future). 

I would appreciate comments from others on the two comments in the `Backward Compatibility` section. I can work on making changes to the RFC afterward.

**Comment by jordandsullivan** [comment]
> Andrea left a comment on the RFC that we should keep the LRE and ZNE inference methods separate. Initially, I thought it would be better to move `mitiq.zne.inference` to `mitiq.inference` in order to avoid defining another module for the multivariate extrapolation methods.

I agree that it would make sense to move all the inference methods into their own module as you describe @purva-thakre .

**Comment by purva-thakre** [comment]
Current version of the RFC (without the linked Jupyter notebook) was accepted during this week's community call.

**Review by cosenal — APPROVED** [review]
Merging this, given that the RFC has been accepted.

**Pull request merged**
