### PR TITLE
Reformat ghz_circuit.py docs

### LINKED ISSUE #1097: Fix docs for GHZ circuit
Pre-Report Checklist
--------------------

- [x] I am running the latest version of mitiq
- [x] I checked to make sure that this bug has not already been reported

Issue Description
-----------------

API doc for GHZ Circuits is not properly formatted, the new lines are bulleted when they are part of the previous line.

How to Reproduce
----------------

[Click this link to go to the specific page in the API Doc](https://mitiq.readthedocs.io/en/latest/apidoc.html#module-mitiq.benchmarks.ghz_circuits)

Environment Context
-------------------

N/A (none needed, not a system bug)

### PR DESCRIPTION
**Pull request by Rahul-Mistri**
Description
-----------
Fixes #1097
Reformatted docstring related to bug.

Checklist
-----------

Check off the following once complete (or if not applicable) after opening the PR. The PR will be reviewed once this checklist is complete and all tests are passing.

- [x] I added unit tests for new code.
- [x] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [x] I used [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings for functions.
- [x] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.

If some items remain, you can mark this a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

Tips
----

- If the validation check fails:

    1. Run `make check-types` (from the root directory of the repository) and fix any [mypy](https://mypy.readthedocs.io/en/stable/) errors.

    2. Run `make check-style` and fix any [flake8](http://flake8.pycqa.org) errors.

    3. Run `make format` to format your code with the [black](https://black.readthedocs.io/en/stable/index.html) autoformatter.

  For more information, check the [Mitiq style guidelines](https://mitiq.readthedocs.io/en/stable/contributing.html#style-guidelines).
  
- Write "Fixes #XYZ" in the description if this PR fixes Issue #XYZ.

### CODE REVIEW

**Review by nathanshammah — APPROVED** [review]
The issue of the signature bullet points seems fixed to me now. 
Below a snapshot from the current docs (that are rendered in the checks run above, reachable [here](https://github.com/unitaryfund/mitiq/pull/1098#:~:text=Docs%20build%20succeeded!-,Details,-Merging%20is%20blocked)).
signature-ghz

Looks good to me, thanks @Rahul-Mistri.

**Comment by Rahul-Mistri** [comment]
@nathanshammah I reset my fork to be up to date with this repo, but it seems to have altered this one and removed the change... Not sure why, do you know how I can undo this?

**Comment by nathanshammah** [comment]
I am not sure. It may be due to the fact that you opened the PR from your master. It's always best practice to work on a branch that is not master. Even with administrator privileges, I cannot reopen this PR. I suggest you just open a new PR from a branch that is not master, with the same content as this one.

**Comment by nathanshammah** [comment]
@Rahul-Mistri any update on this?

**Comment by Rahul-Mistri** [comment]
@nathanshammah Will push it now :+1:

**Pull request closed without merging**
