### PR TITLE
Fix executor and update wording of DDD tutorial

### PR DESCRIPTION
**Pull request by Misty-W**
## Description

Change noise level to 0 for `is_noisy=False` condition of executor. This wasn't caught earlier because `skip-execution` tags were used to minimize build time.

Also, clarify the improvement is very slight and emphasize it is for circuit depths above 3.

---

### License

- [X] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

Before opening the PR, please ensure you have completed the following where appropriate.
- [X] I added unit tests for new code.
- [X] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [X] I used [Google-style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) docstrings for functions.
- [X] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.
- [X] Added myself / the copyright holder to the AUTHORS file

### CODE REVIEW

**Comment by andreamari** [comment]
Hi @Misty-W, I have some suggestions in  #1658, which is a PR pointing to this PR.

**Comment by Misty-W** [comment]
Thanks for the suggestions in #1658 @andreamari !  I merged them into this PR and updated the thumbnail accordingly. Looking much better!

**Review by andreamari — CHANGES_REQUESTED** [review]
Thanks for updating the figure! I didn't notice the `[skip-execution]` tags and so I expected the plot to be automatically generated.

With the current code the execution takes just a few seconds (10 seconds on my laptop). 
What about if we remove all the `[skip-execution]` tags, such that output text and the plot are automatically generated?

All the rest looks good to me!

**Comment by Misty-W** [comment]
`skip-execution` tags removed. Docs failure is due to broken link to myst parser guide, fixed in #1661

**Review by andreamari — APPROVED** [review]

**Comment by natestemen** [comment]
Nice!

**Pull request merged**
