### PR TITLE
Bump Cirq

### PR DESCRIPTION
**Pull request by rmlarose**
Description
-----------

Checklist
-----------

Check off the following once complete (or if not applicable) after opening the PR. The PR will be reviewed once this checklist is complete and all tests are passing.

- [ ] I added unit tests for new code.
- [ ] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [ ] I used [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings for functions.
- [ ] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.

If some items remain, you can mark this a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

Tips
----

- If the validation check fails:

    1. Run `make check-types` (from the root directory of the repository) and fix any [mypy](https://mypy.readthedocs.io/en/stable/) errors.

    2. Run `make check-style` and fix any [flake8](http://flake8.pycqa.org) errors.

    3. Run `make format` to format your code with the [black](https://black.readthedocs.io/en/stable/index.html) autoformatter.

  For more information, check the [Mitiq style guidelines](https://mitiq.readthedocs.io/en/stable/contributing.html#style-guidelines).
  
- Write "Fixes #XYZ" in the description if this PR fixes Issue #XYZ.

### CODE REVIEW

**Comment by nathanshammah** [comment]
There seems to be two errors:

1. In docs, 

```
Exception occurred:
48
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/sphinx/ext/autodoc/mock.py", line 151, in mock
49
    sys.meta_path.remove(finder)
50
ValueError: list.remove(x): x not in list
51
The full traceback has been saved in /tmp/sphinx-err-_ilna3zj.log, if you want to report the issue to the developers.
52
Please also report this if it was a user error, so that a better error message can be provided next time.
53
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
54
make[1]: *** [Makefile:20: html] Error 2
55
make[1]: Leaving directory '/home/runner/work/mitiq/mitiq/docs'
56
make: *** [Makefile:34: docs] Error 2
57
Error: Process completed with exit code 2.
```

2. In ubuntu testing, especially with qiskit and measurement-related tests (start here).

**Comment by vtomole** [comment]
This was fixed by https://github.com/quantumlib/Cirq/pull/4467

**Comment by rmlarose** [comment]
Thanks for the ping @vtomole, nice!

**Comment by vtomole** [comment]
👍

**Pull request closed without merging**
