### PR TITLE
Set changelog to v0.6.0 dev

### PR DESCRIPTION
**Pull request by andreamari**

### CODE REVIEW

**Review by crazy4pi314 — APPROVED** [review]
LGTM

**Review by nathanshammah — COMMENTED** [review]
Shouldn't we change also version.txt into 0.6.0dev?

**Comment by crazy4pi314** [comment]
@nathanshammah I fixed the version.txt, sorry I forgot that b4 approving.

**Comment by andreamari** [comment]
Good point, I forgot about `version.txt`. Thanks @crazy4pi314 for updating it.

**Pull request merged**
