### PR TITLE
Implement conversions of IonQ native gates for Braket

### PR DESCRIPTION
**Pull request by yitchen-tim**
## Description

Implement conversions of IonQ native gates for Braket so that Mitiq can understand circuits with IonQ native gates. 

---

### License

- [x] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

Before opening the PR, please ensure you have completed the following where appropriate.
- [x] I added unit tests for new code.
- [x] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [x] I used [Google-style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) docstrings for functions.
- [ ] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.
- [x] Added myself / the copyright holder to the AUTHORS file

### CODE REVIEW

**Comment by yitchen-tim** [comment]
I'm not sure why the "greeting" test fails. The error message is hard to decode for me.

**Comment by andreamari** [comment]
Many thanks @yitchen-tim! 
Do you think we should wait for the Cirq update (inversions of IonQ gate) to happen before merging this PR?
I don't think merging this PR before a Cirq update is harmful, in the worst case GPI/MS gates won't work in situations where the inverse is necessary. Currently they don't work in all cases.

Second question: In the current code we manually convert other native IonQ gates e.g. V/Vi. Do you think it would be better to use `cirq_ionq.ionq_native_gates` ? 

Taking this reasoning to the extreme, probably Cirq has some conversions functions that can be directly applied to circuits and not to gates.  

We don't have to address those questions in this PR! I am just asking if you think there is space for further improvements.

**Comment by yitchen-tim** [comment]
I don't think we should to convert all gates into native gates at the gate level since the conversion may not be optimal. Doing it at the circuit level is good (something like `cirq.optimize_for_target_gateset`). If there is a transpiler that do anything more than simple gate-to-gate conversions between python packages, I think the pipeline should always be first conversion/transpilation and then circuit folding. If the order is reserve, the transpiler would interfere the with circuit folding.

Also, if there is going to be a transpiler, I think it's better to make it optional rather than automated in the pipeline. There are two types of users: (1) those who directly program in native gates so they don't want their circuit compiled further, and (2) those who program in standard gate set but want to use error mitigation. For (2), users would want transpiler, but not for (1).

**Comment by yitchen-tim** [comment]
For this PR, I think it's good to merge. For those who does `pip install cirq`, they still could not use it because there is no gate inverse, but the gate inverse is already merged in Cirq master branch, so users can use it with github version of Cirq.

Also, do you know why the "greeting" test fails?

**Comment by purva-thakre** [comment]
>  do you have any tip to fix the "greeting" test?

@yitchen-tim I don't think `Greetings` failing is because of something you did. 

This seems to be an issue with Github Actions : https://github.com/actions/first-interaction/issues/101

**Review by andreamari — APPROVED** [review]
LGTM! Thanks also for your ideas about transpilation/conversions. I agree with all your comments.

**Comment by nathanshammah** [comment]
Thanks @yitchen-tim!

**Pull request merged**
