### PR TITLE
Draft workflow to run change specific tests

### LINKED ISSUE #1806: Make test suite run only on specific changes for draft PRs
## Issue Description

I'd like pushes to an open draft PR to provide feedback more quickly, and concisely. It takes a long time, can be interrupted by subsequent pushes, and uses excessive resources.

## Proposed Solution

Write a workflow that checks for draft PRs, add in workflow items to detect changed files/directories, then use the `make test-%` wildcard to test only changed files. On the trigger change from draft -> ready for review, run the entire test suite.

## Additional References

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
https://github.com/orgs/community/discussions/25722

### PR DESCRIPTION
**Pull request by Aaron-Robertson**
## Description

Fixes #1806 

---

### License

- [x] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

Before opening the PR, please ensure you have completed the following where appropriate.
- [x] I added unit tests for new code.
- [x] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [x] I used [Google-style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) docstrings for functions.
- [x] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.
- [x] Added myself / the copyright holder to the AUTHORS file

### CODE REVIEW

**Comment by andreamari** [comment]
@Aaron-Robertson , could you do a commit (even an empty one) to re-trigger the short tests for a draft-like PR?

**Comment by Aaron-Robertson** [comment]
@andreamari Got this one set to a draft and merged in the latest release. Looks like the build tests are passing, all in under 10 minutes as expected! Still getting a docs build linkcheck error though, and I'm not seeing why as the docs themselves appear completely fine and I don't see a broken link.

**Review by andreamari — APPROVED** [review]
Thanks @Aaron-Robertson, the speedup advantage is quite big! 
Reducing tests can be risky, but this happens only for draft PRs and we can even revert this change in the case we encounter relevant unexpected drawbacks.  So, for me looks good!

**Comment by Aaron-Robertson** [comment]
Sounds good @andreamari! Happy to move forward and find edge cases as we go, but I could create a few branches off this one with current PRs so we can see it in action and find any obvious ones before release. Just let me know if you have a preference!

**Review by Misty-W — APPROVED** [review]
I’m good with the PR as-is. Thanks Aaron!

**Pull request merged**
