### PR TITLE
Update Qibo demo snippet on v0.34 changelog 

### PR DESCRIPTION
**Pull request by Misty-W**
## Description

Now that Qibo is integrated with Mitiq, we don't need to use `convert_to_mitiq` for Qibo circuits.

---

### License

- [x] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

Before opening the PR, please ensure you have completed the following where appropriate.
- [x] I added unit tests for new code.
- [x] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [x] I used [Google-style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) docstrings for functions.
- [x] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.
- [x] Added myself / the copyright holder to the AUTHORS file

### CODE REVIEW

**Review by natestemen — CHANGES_REQUESTED** [review]
Thanks for removing this! I'm still getting an error[^1] when trying to run this example:
```
TypeError: unsupported operand type(s) for /: 'QuantumState' and 'int'
```
Is it running on your side? If it's not, it looks like we will need to use a different executor.

[^1]: We need to import `gates` from `qibo` as well as `import mitiq` to make sure it runs, but then after those issues, we still get the type error :/.

**Comment by Misty-W** [comment]
I'm looking at this and realize now there are more problems- the circuit is trivial, no noise applied, and I'm not sure where the executor error is coming from.

**Comment by cosenal** [comment]
Closing this as v0.34 has been released already, and it looks like a working version of the Qibo snippet [made it into the changelog](https://github.com/unitaryfund/mitiq/blob/main/CHANGELOG.md#version-0340).

**Comment by natestemen** [comment]
The code snippet in the changelog is still broken (I don't think it ever worked). Whether it's worth fixing, I'm not sure, but I don't love the fact that we have code in the changelog (which, IMO, is a suggestion for users to run) which does not run.

@Misty-W do you still want to update this?

**Comment by Misty-W** [comment]
> The code snippet in the changelog is still broken (I don't think it ever worked). Whether it's worth fixing, I'm not sure, but I don't love the fact that we have code in the changelog (which, IMO, is a suggestion for users to run) which does not run.
> 
> @Misty-W do you still want to update this?

I’ll remove it.

**Comment by cosenal** [comment]
Sorry, I closed this PR because I thought the snippet from the changelog had been fixed already.

Anyway, I looked at the code of the snippet. It doesn't make sense to me even before executing it, and that's neither in the original form, nor in the form of this PR.

In the original form, we are converting the circuit from Qibo to Cirq, and then using a `circuit.execute()` executor function, which implies that Cirq has an `execute` function, but it doesn't look like that's the case.

On the other hand, in the form of this PR, we are trivially using the Qibo [execute()](https://qibo.science/qibo/stable/_modules/qibo/models/circuit.html#Circuit.execute) function, which does exist, but doesn't even have the signature required, i.e., it returns an object that is not Mitiq's QuantumResult. 

In both cases, I don't see why this should work in the simple form of the snippet, unless we write a non-trivial executor, similar to [the one](https://github.com/unitaryfund/mitiq/blob/832daf992493101d10e35c5d3617c54de513def3/docs/source/examples/qibo-noisy-simulation.md#defining-the-executor) in the «Error mitigation with Qibo» example.

**Comment by natestemen** [comment]
> In both cases, I don't see why this should work in the simple form of the snippet

My guess is that it went untested in https://github.com/unitaryfund/mitiq/pull/2191. Maybe a good practice to help eliminate this in the future is require 2 reviewers for release notes?

**Pull request closed without merging**
