### PR TITLE
Port BQSKit example to 1.0 release

### PR DESCRIPTION
**Pull request by natestemen**
## Description

fixes https://github.com/unitaryfund/mitiq/issues/1520

As part of this PR I have added the `BQSKIT_DOC_CHECK_OVERRIDE` environment variable to RTD. This is a temporary fix issued by the BQSKit devs which might be fixed in a future release. We should watch out for that, and remove accordingly.

### CODE REVIEW

**Comment by nathanshammah** [comment]
@natestemen do you want to move this from draft status to open?

**Comment by nathanshammah** [comment]
Happy to review!

**Comment by natestemen** [comment]
I need help fixing the problems on RTD before it's ready for review. Let me know if you can help me because I'm stuck.

**Comment by nathanshammah** [comment]
Just to add also here that build works correctly locally on my machine.

**Comment by andreamari** [comment]
FYI: Another way of setting environment variables for readthedocs is here: https://readthedocs.org/dashboard/mitiq/environmentvariables/

But what you did seems to work too!

**Pull request merged**
