### PR TITLE
Review RFC for Probabilistic Error Amplification technique

### PR DESCRIPTION
**Pull request by Misty-W**
RFC ready for review:
https://docs.google.com/document/d/1l-74EFdMA0CSFUpHjqCyQYb3ZKCmY77seB1_mOZo5Co/edit?tab=t.0

### License

- [x] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

Before opening the PR, please ensure you have completed the following where appropriate.

- [ ] I added unit tests for new code.
- [ ] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [ ] I used [Google-style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) docstrings for functions.
- [x] I [updated the documentation](../blob/main/docs/CONTRIBUTING_DOCS.md) where relevant.
- [x] Added myself / the copyright holder to the AUTHORS file

### CODE REVIEW

**Comment by natestemen** [comment]
Purva's comments have been resolved, and I've added mine. Looking good! Should be ready to merge this shortly.

@Misty-W can you add a row to the [techniques table in the README](https://github.com/unitaryfund/mitiq?tab=readme-ov-file#error-mitigation-techniques) to show PEA will be under development?

**Comment by purva-thakre** [comment]
Also add the RFC here: https://mitiq.readthedocs.io/en/stable/contributing.html#list-of-accepted-rfcs

**Comment by Misty-W** [comment]
@natestemen @purva-thakre this is ready to go in today's release if you agree!

**Review by purva-thakre — APPROVED** [review]
Thanks Misty!

**Pull request merged**
