### PR TITLE
Include calculated error in calibrator logs

### LINKED ISSUE #2014: Include calculated error in calibrator logs
Along with having the good/bad indicators, it would be nice to have a column which included the actual error.

Idea by @andreamari

### PR DESCRIPTION
**Pull request by kozhukalov**
## Description

Calibration log table is extended with errors calculated
during calibration and sorted so that best
techniques are on the top of the table.

Fixes #2014

---

### License

- [x] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

Before opening the PR, please ensure you have completed the following where appropriate.
- [ ] I added unit tests for new code.
- [ ] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [ ] I used [Google-style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) docstrings for functions.
- [ ] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.
- [ ] Added myself / the copyright holder to the AUTHORS file

### CODE REVIEW

**Review by natestemen — COMMENTED** [review]
Really nice work Vladimir! Thanks for adding this!

I think we should add the errors by default as part of the table instead of adding the additional `log_errors` option. IMO if someone is asking for logs, lets provide everything!

**Comment by kozhukalov** [comment]
Ok, I'll make it default. 

The only concern here is backward compatibility. Some people probably try to parse the performance log with their automation tools and we can break their pipelines. However I am new in Mitiq. Not sure how important it is.

**Comment by kozhukalov** [comment]
I am not sure what is wrong with the docs/readthedocs.org:mitiq check. It says `Read the Docs build failed!` but the build looks successful. @natestemen can you please help me understand what I should fix to make it green?

**Comment by purva-thakre** [comment]
@kozhukalov This is a bug in RTD. When there are multiple PRs running checks at the same time, RTD fails to build the documentation in all of them. 

I do not know a way to re-trigger this build besides making a dummy commit.

**Comment by kozhukalov** [comment]
@purva-thakre The issue is that even if this RTD job is green it the becomes red later when another PR runs RTD job. So I think it should not be voting.

**Review by natestemen — APPROVED** [review]
Awesome work with this! Thanks for the nice simple upgrade. :shipit:

**Pull request merged**
