### PR TITLE
Fixed typo in documentation formula

### PR DESCRIPTION
**Pull request by ZhaoyiLi-HekJukZaaiZyuJan**
Description
-----------

Fixed minor typo in a formula. (Deleted an extra bracket that is not closed.)

Checklist
---------

Check off the following once complete (or if not applicable) after opening the PR. The PR will be reviewed once this checklist is complete and all tests are passing.

- [ ] I added unit tests for new code.
- [ ] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [ ] I used [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings for functions.
- [x] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.
- [ ] Added myself / the copyright holder to the AUTHORS file

If some items remain, you can mark this a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

License
-------

- [x] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

Tips
----

- If the validation check fails:

    1. Run `make check-types` (from the root directory of the repository) and fix any [mypy](https://mypy.readthedocs.io/en/stable/) errors.

    2. Run `make check-style` and fix any [flake8](http://flake8.pycqa.org) errors.

    3. Run `make format` to format your code with the [black](https://black.readthedocs.io/en/stable/index.html) autoformatter.

  For more information, check the [Mitiq style guidelines](https://mitiq.readthedocs.io/en/stable/contributing.html#style-guidelines).

- Write "Fixes #XYZ" in the description if this PR fixes Issue #XYZ.

### CODE REVIEW

**Comment by andreamari** [comment]
Thanks @ZhaoyiLi-HekJukZaaiZyuJan !
Could you please edit the title of this pull request (Nitan) to make it more explicit. E.g. _Fix a typo in formula documentation_ or anything similar?
You also need to tick the licence agreement (in the PR description above).
Feel free to add your name or GitHub username [here](https://github.com/unitaryfund/mitiq/blob/master/AUTHORS).

**Comment by ZhaoyiLi-HekJukZaaiZyuJan** [comment]
> Thanks @ZhaoyiLi-HekJukZaaiZyuJan !
> Could you please edit the title of this pull request (Nitan) to make it more explicit. E.g. _Fix a typo in formula documentation_ or anything similar?
> You also need to tick the licence agreement (in the PR description above).
> Feel free to add your name or GitHub username [here](https://github.com/unitaryfund/mitiq/blob/master/AUTHORS).

Done.

**Comment by nathanshammah** [comment]
Hi @ZhaoyiLi-HekJukZaaiZyuJan, the title of the pull request (top of this page) still reads "Nitan".

**Comment by ZhaoyiLi-HekJukZaaiZyuJan** [comment]
> Hi @ZhaoyiLi-HekJukZaaiZyuJan, the title of the pull request (top of this page) still reads "Nitan".

Oh sorry I didn't realize that. Just fixed it!

**Comment by andreamari** [comment]
Hi @ZhaoyiLi-HekJukZaaiZyuJan, at the top of this page there is a section called "Licence". In that place you should tick the item that starts with "I license this contribution under the terms of the GNU GPL...".

There are conflicts between your PR and the master branch that need to be resolved. Online you can find many guides explaining how to deal with this problem. E.g.: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts

We can also help if necessary.

**Comment by ZhaoyiLi-HekJukZaaiZyuJan** [comment]
Hi,
I think I’ve already ticked that?
—Zhaoyi


On Apr 29, 2022, at 6:55 AM, Andrea Mari ***@***.******@***.***>> wrote:



Hi @ZhaoyiLi-HekJukZaaiZyuJan<https://github.com/ZhaoyiLi-HekJukZaaiZyuJan>, at the top of this page there is a section called "Licence". In that place you should tick the item that starts with "I license this contribution under the terms of the GNU GPL...".

The failing test (test / docs) can be ignored since it has been fixed in a different PR.

**Comment by nathanshammah** [comment]
@ZhaoyiLi-HekJukZaaiZyuJan, please tick all the checkboxes above in the first post of this page. Also, as Andrea pointed out, there is a conflict to resolve with the version file.

**Review by andreamari — APPROVED** [review]
Thanks @ZhaoyiLi-HekJukZaaiZyuJan, and congratulations for your first PR to Mitiq! 
:tada:

**Pull request merged**
