### PR TITLE
Added citiation file for the repo

### LINKED ISSUE #1154: Add citiation file for the repo
Issue Description
-----------------

Last year, GH added support for a citation file that then adds UI elements to the repo pages to help folks generate a citation for the project. Blog announcing: https://github.blog/2021-08-19-enhanced-support-citations-github/

Proposed Solution
-----------------

Add a `.cff` file for the mitiq paper.

Additional References
---------------------
Docs for the feature: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files#about-citation-files

### PR DESCRIPTION
**Pull request by RubidgeCarrie**
Description
-----------

Added citation file for the repository giving the preferred citation as the Mitiq article version 3 https://arxiv.org/abs/2009.04417. Fixes #1154

Checklist
---------

Check off the following once complete (or if not applicable) after opening the PR. The PR will be reviewed once this checklist is complete and all tests are passing.

- [X ] I added unit tests for new code.
- [X ] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [X ] I used [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings for functions.
- [X ] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.
- [X] Added myself / the copyright holder to the AUTHORS file

If some items remain, you can mark this a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

License
-------

- [X ] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

Tips
----

- If the validation check fails:

    1. Run `make check-types` (from the root directory of the repository) and fix any [mypy](https://mypy.readthedocs.io/en/stable/) errors.

    2. Run `make check-style` and fix any [flake8](http://flake8.pycqa.org) errors.

    3. Run `make format` to format your code with the [black](https://black.readthedocs.io/en/stable/index.html) autoformatter.

  For more information, check the [Mitiq style guidelines](https://mitiq.readthedocs.io/en/stable/contributing.html#style-guidelines).

- Write "Fixes #XYZ" in the description if this PR fixes Issue #XYZ.

### CODE REVIEW

**Comment by crazy4pi314** [comment]
Awesome! I am taking a look at it now 💖

**Review by crazy4pi314 — CHANGES_REQUESTED** [review]
Thanks so much @RubidgeCarrie this is a great start, both on the issue and your open source journey! 💖 I apologize for so many comments, but I was going and learning more about this new file format spec. I think the main thing was that we have a paper on the project which is what we want people to cite here (not always the case, but we don't want to split the citations). I also found an online tool [here](https://citation-file-format.github.io/cff-initializer-javascript/#/) that I used as a reference for the syntax I proposed below. I think all that's left is filling out a bit more about the authors, and then It'll be good to merge!

**Comment by RubidgeCarrie** [comment]
Thank you so much @crazy4pi314  for all the comments, it was very helpful learning how to use them to update the code! I am just in the process of updating the author's information. I can't seem to see the way you mentioned to get the information off arxiv but I am not sure if this is because I am not registered.

**Review by crazy4pi314 — APPROVED** [review]
TYSM! 🥳 It is going to be much easier now for folks to find the right citation for Mitiq <3

**Comment by RubidgeCarrie** [comment]
Hi Sarah @crazy4pi314 I am glad it helped a bit, it was a great way to learn focusing on GitHub and not the code! I should probably have changed to a draft version since I was just still fighting with the accents for Max Gordon's University (I am not sure how they should be represented in the cff file) and hadn't removed the space for an orcid for Dr. William Zeng but these will be minor corrections at some point.

**Pull request merged**
