### PR TITLE
[Test codecov]

### PR DESCRIPTION
**Pull request by grmlarose**
Description
-----------

Checklist
-----------

Check off the following once complete (or if not applicable). The PR will be reviewed once this
checklist is complete and all tests are passing.

- [ ] I added unit tests for new code.
- [ ] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [ ] I used [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings for functions.
- [ ] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.
- [ ] I updated the [changelog](https://github.com/unitaryfund/mitiq/blob/master/CHANGELOG.md) including author and PR number (@username, gh-xxx)

If some items remain, you can mark this a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

Tips
----

- If the validation check fails:
  1. Run `make check-style` (from the root directory
  of the repository) and fix any [flake8](http://flake8.pycqa.org) errors.
  2. Run `make format` to format your code with the [black](https://black.readthedocs.io/en/stable/index.html)
  autoformatter.
- Write "Fixes #XYZ" in the description if this PR fixes Issue #XYZ.

### CODE REVIEW

**Comment by rmlarose** [comment]
So all PRs after #569 are [missing base reports](https://docs.codecov.io/docs/error-reference#missing-base-commit).

image

[Link](https://app.codecov.io/gh/unitaryfund/mitiq/pulls?page=2&order=-pullid) to that page (UF only I think). Inspecting any reveals that codecov is using #563 as the base commit to compare against. 

image

I think there are two options to fix this:

1. [Rebase or merge target](https://docs.codecov.io/docs/comparing-commits#rebase-vs-merge-target). 
    - TBH I'm not really sure what the docs are saying here - make a PR from the last successfully uploaded base report? This seems weird and hacky. From the [error reference](https://docs.codecov.io/docs/error-reference#missing-base-commit): 
    - > Best Practice: Always fork a branch from a successful CI commit that has coverage uploaded, as illustrated below.
2. [Erase history](https://docs.codecov.io/docs/deleting-and-erasing-repos-from-codecov#:~:text=If%20you%20desire%20to%20clear,use%20the%20Delete%20Data%20option.) to start fresh.
    - This kinda seems easier and more appropriate as its a problem with the tool. 

Either option has the problem that if this happens again we have to do either (1) or (2) again. (Can we use a different tool for coverage?...)

**Comment by rmlarose** [comment]
cc @willzeng @nathanshammah @crazy4pi314

**Comment by crazy4pi314** [comment]
Can we just upload the missing report? Like check out that commit, generate the report and manually upload?

**Comment by rmlarose** [comment]
Added to milestone 0.8.0 to track this.

**Comment by crazy4pi314** [comment]
Tagging in @ckissine 🎉

**Comment by ckissane** [comment]
I might work on this

**Comment by rmlarose** [comment]
See #645.

**Pull request closed without merging**
