### PR TITLE
Fix a few html rendering problems of the PEC example.

### PR DESCRIPTION
**Pull request by andreamari**
Description
-----------
The [current html rendering](https://mitiq.readthedocs.io/en/latest/examples/pec-tutorial.html) of the PEC example has some problems (not appearing in Jupyter):

- Some latex equations are bad visualized. 
- The link to sub-sections don't work in the html page.

This PR should fix both problems.
Preview the result after the changes of this PR: https://mitiq.readthedocs.io/en/fix-pec-example/examples/pec-tutorial.html

### CODE REVIEW

**Review by crazy4pi314 — APPROVED** [review]
LGTM, good catch!

**Comment by crazy4pi314** [comment]
Not sure why the docs build is failing though...

**Comment by andreamari** [comment]
> Not sure why the docs build is failing though...

It is unrelated to this PR.  There is a problem with some links detected as borken (but are not borken), so I am not sure how to fix it. I tried with the last commit but it didn't work.

**Comment by andreamari** [comment]
I created too many commits that didn't fix the problem. So I close this PR and reopen with a clean one (#894).
@crazy4pi314  Could you review/approve #894 too? It's the same without dirty commits.

**Pull request closed without merging**
