### PR TITLE
Doc build debugger warning

### LINKED ISSUE #1826: Debugger warning about frozen modules in docs build
The following warning occurs at every notebook execution in the docs build:

> 0.00s - Debugger warning: It seems that frozen modules are being used, which may
> 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
> 0.00s - to python to disable frozen modules.
> 0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

See https://github.com/unitaryfund/mitiq/actions/runs/4921156704/jobs/8790708057?pr=1745 for an example.

See https://stackoverflow.com/questions/75114841/debugger-warning-from-ipython-frozen-modules for solution options.

### PR DESCRIPTION
**Pull request by purva-thakre**
Fixes #1826

### CODE REVIEW

**Comment by purva-thakre** [comment]
This one is ready to be merged.

**Comment by andreamari** [comment]
Hi @purva-thakre, your solution LGTM! 
However, I don't think this will fix https://github.com/unitaryfund/mitiq/issues/1846 since the proposed fix only acts during the Github workflow and not in a local environment.

So I would approve this PR after changing the current description from:
Fixes https://github.com/unitaryfund/mitiq/issues/1826
Fixes https://github.com/unitaryfund/mitiq/issues/1846

To just:
Fixes https://github.com/unitaryfund/mitiq/issues/1826

Alternately, we could consider inserting `PYDEVD_DISABLE_FILE_VALIDATION=1` in a different place, e.g. in the definition of the  `make docs` command. But I am not sure about the drawbacks of switching off warnings in the local computer users without their explicit consent.

**Comment by purva-thakre** [comment]
@andreamari Good catch!

Let's keep this issue specific to workflows then. One possible solution for #1846 would be to update the docs with instructions on how to disable the warnings if the user wishes to do so.

**Review by andreamari — APPROVED** [review]
LGTM!

**Pull request merged**
