### PR TITLE
Correct QSE module name in diagram

### PR DESCRIPTION
**Pull request by jordandsullivan**
## Description

The old diagram for QSE docs said `mitiq.subspace_expansion`, but the correct module name is `mitiq.qse`. Updated diagram to say `mitiq.qse`, added versions to the images, updated references to the old image to point to v2.

---
### License

- [x] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

Before opening the PR, please ensure you have completed the following where appropriate.

- [ ] I added unit tests for new code.
- [ ] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [ ] I used [Google-style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) docstrings for functions.
- [ ] I [updated the documentation](../blob/main/docs/CONTRIBUTING_DOCS.md) where relevant.
- [ ] Added myself / the copyright holder to the AUTHORS file

### CODE REVIEW

**Review by Misty-W — APPROVED** [review]
LGTM, thanks Jordan!

**Comment by natestemen** [comment]
Any reason for keeping around the old image _and_ adding a new one?

**Comment by jordandsullivan** [comment]
> Any reason for keeping around the old image _and_ adding a new one?

@cosenal requested it here: https://github.com/unitaryfund/mitiq/issues/2272#issuecomment-2044336266. Maybe he wants to share more of the motivation?

**Comment by cosenal** [comment]
@jordandsullivan by _original file_, I meant whatever @natestemen meant in https://github.com/unitaryfund/mitiq/issues/2272#issue-2231881474, that is, the vectorial graphic file that was used to generate the png. I didn't mean v1 of the same png.

**Comment by jordandsullivan** [comment]
Ah, my misunderstanding. I'll delete the old one :)

**Pull request merged**
