### PR TITLE
More explanatory titles in documentation's guide

### PR DESCRIPTION
**Pull request by nathanshammah**
Address #260 with more user-oriented titles.

### CODE REVIEW

**Comment by willzeng** [comment]
@nathanshammah There are some conflicts here. I'm happy to review once those have been resolved. These changes generally look good to me.

**Comment by nathanshammah** [comment]
This PR is now ready for review.

- Made the top menu bar more readable and added structure with additional table of contents, which in the pydata theme for Sphinx we are using, adds a nice menu on the left on all nested pages, on top of the summary menu pages.  

- Restructured the "Guide" pages to show the above mentioned nice menu on the left, adding a new `zne` table of contents. 

- Restructured the "Contributing" pages adding a `toc_contributing.rst` table of contents to add a nice menu. on the left menu bar of the html page. Renamed the related `Markdown` and `RST` files so that the url are nicer, especially for the rst files that import the markdown files `README.md`,  `CONTRIBUTING.md`, `CONTRIBUTING_DOCS.md` and now including the `CODE_OF_CONDUCT.md`. I will tackle in a follow-up PR the issue #237, adding a new page under the "Contributing" for instuctions on version release.  

- Added a "Citing" button in the menu, with a page that contains a LaTeX bibliographic entry that can be copied from the html page and has a linked bibtex file, `mitiq.bib`. This page contains now the github url as reference and will be updated with the arXiv reference. 

- Updated the change log including the 0.1a1 and 0.1a2 pre-releases.

**Comment by nathanshammah** [comment]
Since I merged together in the same file the "factories" and "folding" guide, I then had a mismatch in terms of numbering of files, "guide_04-folding.rst", "guide_05-factories.rst" being replaced by a "*zne.rst" file. This prompted me to delete all numbers from the guide files titles, as this shows that it is much more maintaible without them. This is also for non-breaking links that we want to work on Read the Docs and be as persistent as possible, i.e. not only `https://mitiq.readthedocs.io/en/latest/guide/guide_06-error-mitigation.html` is a bit ugly URL, but as we may shuffle the order of things, it may break in the future. 

The reason why I added the numbers was also due to the way that `pybib` parses files, in alphabetical order, and the way references are added. But using the `zz_references` seems to work fine.

**Comment by willzeng** [comment]
@nathanshammah I built the docs locally and noticed a few things:

[1] It looks like we might have lost links to the getting started guide? This is what I see on the index.html page:
image
Getting started should be very prominent in the docs.

[2] References still has a different header bar than the other pages:
image

**Comment by nathanshammah** [comment]
Thanks all! @willzeng I reduced the TOC depth in this PR as suggested.

**Pull request merged**
