### PR TITLE
Updated link to mitiq logo

### PR DESCRIPTION
**Pull request by jordandsullivan**
## Description

Updated the link to the mitiq logo image in the Readme. This fixes the broken link failing to display the logo in the documentation: https://mitiq.readthedocs.io/en/stable/. 

This fix works on my local build.

---

### License

- [x] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

Before opening the PR, please ensure you have completed the following where appropriate.

- [ ] I added unit tests for new code.
- [ ] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [ ] I used [Google-style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) docstrings for functions.
- [ ] I [updated the documentation](../blob/main/docs/CONTRIBUTING_DOCS.md) where relevant.
- [ ] Added myself / the copyright holder to the AUTHORS file

### CODE REVIEW

**Review by cosenal — APPROVED** [review]

**Comment by jordandsullivan** [comment]
I am not sure how to trigger the docs to rebuild from source on https://mitiq.readthedocs.io/en/stable/ though. Does this only happen once per milestone?

**Comment by purva-thakre** [comment]
> Does this only happen once per milestone?

On stable, yes. You can only see the changes after each milestone. 

I don't see the changes from this PR in the latest version though: https://mitiq.readthedocs.io/en/latest/

**Comment by jordandsullivan** [comment]
Hm, odd. Is there an extra step that needs to be triggered manually?

**Comment by purva-thakre** [comment]
I don't think so. The merged PR should have shown up in the latest version. Maybe there's another reason for the broken logo.

**Comment by cosenal** [comment]
The problem is that RTD latest points to `master` and not `main`

**Comment by jordandsullivan** [comment]
I see others have had this issue too: https://github.com/readthedocs/readthedocs.org/issues/7907

**Comment by cosenal** [comment]
We can just go to our RTD profile and fix it manually, but I don't have the credentials. I asked in the our internal chat.

**Comment by cosenal** [comment]
Fixed it. [Build](https://readthedocs.org/projects/mitiq/builds/24238299/) is in progress now. As soon as it's done, latest should point to main. Thanks for spotting this.

**Pull request merged**
