### PR TITLE
Add CDR example to docs + small change to `cdr.calculate_observable`

### LINKED ISSUE #693: [CDR] Add documentation on Clifford-based data regression methods
Add the documentation in the user guide about the Clifford-based data regression (CDR) methods, main issue is #477, related PRs to date are #520 and #677 (CDR part two). 
- One could think of a basic subsection structure, based on the different parts of the CDR approach (training, extrapolation)
- Could use sphinx's `autosummary`, where relevant  
- Add references (see #692)

### PR DESCRIPTION
**Pull request by rmlarose**
Description
-----------

Closes #693 with an example showing how to use the CDR API.

I also changed the dictionary/counter key type of measurements to be integers, since this is what Cirq returns by default and I think it's more natural.

Additional docs/examples could be added on generating training circuits and doing the regression.

Checklist
-----------

Check off the following once complete (or if not applicable) after opening the PR. The PR will be reviewed once this checklist is complete and all tests are passing.

- [ ] I added unit tests for new code.
- [ ] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [ ] I used [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings for functions.
- [ ] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.

If some items remain, you can mark this a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

Tips
----

- If the validation check fails:

    1. Run `make check-style` (from the root directory of the repository) and fix any [flake8](http://flake8.pycqa.org) errors.

    2. Run `make format` to format your code with the [black](https://black.readthedocs.io/en/stable/index.html) autoformatter.

  For more information, check the [Mitiq style guidelines](https://mitiq.readthedocs.io/en/stable/contributing.html#style-guidelines).
  
- Write "Fixes #XYZ" in the description if this PR fixes Issue #XYZ.

### CODE REVIEW

**Comment by rmlarose** [comment]
Not sure what the mysterious warning is but PTAL @andreamari. cc @L-P-B

**Review by L-P-B — COMMENTED** [review]
All looks good to me, Thanks!

**Review by andreamari — COMMENTED** [review]
Thanks @rmlarose! 
As we discussed in the Mitiq meeting, this could become a section of the user Guide instead of being an example.

- If you decide to keep it as an example, this LGTM.
- If you decide to put this in the User Guide, I think we should test the output of the code cells as we do for the rest of the User Guide.

In any case the content looks good to me. Maybe it could be expanded in the future, but this is a good and self-contained starting point.

**Comment by rmlarose** [comment]
I don't think there's enough explanatory text to be a guide, so let's keep this in examples for now.

**Pull request merged**
