### PR TITLE
Release (PR generated by github action)

### PR DESCRIPTION
**Pull request by andreamari**
This PR was automatically generated by GitHub.

### CODE REVIEW

**Comment by andreamari** [comment]
@crazy4pi314, I followed the guide and I think I successfully made a release on GitHub. However this PR from release to master was automatically generated. Is it expected? Should this be merged?

**Review by crazy4pi314 — APPROVED** [review]

**Comment by crazy4pi314** [comment]
Yeah so this has to get merged back because folks still wanted squash merges, so since release gets squashed, we need that commit on master to have a shared starting point.

**Comment by andreamari** [comment]
Ok, I see. Thanks!

**Comment by andreamari** [comment]
Hi @crazy4pi314, when you merged this PR the `release` branch was automatically deleted. So I'll click on the `restore branch` button and see what happens.

**Comment by crazy4pi314** [comment]
So I didn't delete the branch, it seems we have "delete after merge" set on GitHub which I will disable. I want this to be an active choice to do so

**Pull request merged**
