### PR TITLE
Add clarification for virtualenv files vs mitiq directory

### PR DESCRIPTION
**Pull request by smburdick**
## Description

Adding a line of clarification to allow make checks to perform inside a virtual environment, specifically that virtualenv files and mitiq must be in different directories. Since the documentation should be beginner friendly, this change is warranted.

---

### License

- [x] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

Before opening the PR, please ensure you have completed the following where appropriate.
- [ ] I added unit tests for new code.
- [ ] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [ ] I used [Google-style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) docstrings for functions.
- [x] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.
- [x] Added myself / the copyright holder to the AUTHORS file

### CODE REVIEW

**Review by natestemen — COMMENTED** [review]
Thanks Sam for the comments here. It's really important that we have clear development documentation.

I'm not totally clear on what you're suggesting, however. Would you mind expanding on your suggestion a little so I can better understand what you're suggesting? Spelling it out with CLI commands can sometimes be helpful.

**Comment by smburdick** [comment]
> Thanks Sam for the comments here. It's really important that we have clear development documentation.
> 
> I'm not totally clear on what you're suggesting, however. Would you mind expanding on your suggestion a little so I can better understand what you're suggesting? Spelling it out with CLI commands can sometimes be helpful.

Hi Nate,

When I went to set up mitiq on my own, I could not run flake due to a max recursion depth error. The root cause turned out to be due to the fact that I set up my virtual environment in the same folder as mitiq. The solution to the problem looks like this:

```
mkdir mitiq-venv && cd mitiq-venv
virtualenv [options]
source bin/activate
cd ..
git clone [mitiq-repo]
cd mitiq-repo # Now I'm ready to run the tests
```

**Comment by natestemen** [comment]
Ahh I see what you mean! Thanks for the extra details. I've actually ran into that before as well since I had a virtual environment in the root of mitiq. Since I started using conda for managing environments this hasn't been a problem, but we should be agnostic to the environment management tool.

That said, I think it actually makes sense to have the virtual environment **inside** the root of the project. That way it's kept track of based on where you are in your file system. I think a potential fix could be to modify the command that is run when `make check-style` is run so that it only runs `flake8` on the `mitiq` directory. What do you think of this plan?

**Comment by natestemen** [comment]
Since https://github.com/unitaryfund/mitiq/pull/2222 is now merged I'm not sure if this behavior still exists. @smburdick would you mind checking if running `make format` or `make check-format` on master (with a virtualenv in the root of the mitiq repo) throws a similar sort of error?

**Comment by natestemen** [comment]
Going to close this now, but if it's still a problem with `ruff` let me know and we can get this fixed!

**Pull request closed without merging**
