### PR TITLE
Change custom depolarizing channel in PEC

### LINKED ISSUE #607: Replace the custom depolarizing channel in tests with the cirq.DepolarizingChannel
In some PEC tests we had to define a custom depolarizing channel:

https://github.com/unitaryfund/mitiq/blob/69c588b084d09fd9f2696dc86c64da6b96ef5d8b/mitiq/pec/representations/tests/test_depolarizing.py#L44

since at that time `cirq.DepolarizingChannel` was not compatible with 2-qubit gates.

The Cirq issue has been fixed and so we could replace the custom channel with `cirq.DepolarizingChannel`.

### PR DESCRIPTION
**Pull request by purva-thakre**
Description
-----------
Fixes #607 

Checklist
-----------

Check off the following once complete (or if not applicable). The PR will be reviewed once this
checklist is complete and all tests are passing.
- [x] I updated the [changelog](https://github.com/unitaryfund/mitiq/blob/master/CHANGELOG.md) including author and PR number (@username, gh-xxx)

### CODE REVIEW

**Review by andreamari — APPROVED** [review]
Thanks @purva-thakre for this fix! 
Feel free to update the changelog.

**Comment by purva-thakre** [comment]
@andreamari It's been updated. 

I added a couple of lines to the changelog because it conflicts with an open PR not yet merged (614).

**Comment by nathanshammah** [comment]
The CI actions did not run on this branch and now the master is failing.

**Comment by andreamari** [comment]
I revert this since master was failing due to a previous PR.

**Comment by nathanshammah** [comment]
Ok actually this were running fine.

**Comment by andreamari** [comment]
Ok so I don't revert for the moment.

**Pull request merged**
