### PR TITLE
Zne pec test uniformity

### LINKED ISSUE #668: Move all ZNE unit tests to `mitiq.zne`
There's some hanging around in `mitiq_qiskit` and `mitiq_pyquil`. We decided @ Mitiq meeting that it's better to put these in test files in `mitiq.zne`.

This also makes the testing structure more consistent between `mitiq.zne` and `mitiq.pec` (all PEC tests are in `mitiq.pec`).

### PR DESCRIPTION
**Pull request by andre-a-alves**
Description
-----------
Closes #668
Because the tests were a bit different between the three front-ends, I did not combine tests with pytest.mark.parameterize
The doctring test is still failing, which I understand is due to an unrelated issue.
Two other things worth mentioning:
1. I never got any feedback on my comment about whether we would want to restructure/relocate all tests to take advantage of pyTest's advanced features. Should that be discussed in tomorrow's meeting? Because if we decide that's a good idea, this PR is moot 
2. By moving the tests, a QVM server now needs to be running in order to run "make test" instead of only being required to run "make test-pyquil".

Checklist
-----------

Check off the following once complete (or if not applicable) after opening the PR. The PR will be reviewed once this checklist is complete and all tests are passing.

- [N/A] I added unit tests for new code.
- [N/A] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [N/A] I used [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings for functions.
- [X] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.

If some items remain, you can mark this a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

Tips
----

- If the validation check fails:

    1. Run `make check-style` (from the root directory of the repository) and fix any [flake8](http://flake8.pycqa.org) errors.

    2. Run `make format` to format your code with the [black](https://black.readthedocs.io/en/stable/index.html) autoformatter.

  For more information, check the [Mitiq style guidelines](https://mitiq.readthedocs.io/en/stable/contributing.html#style-guidelines).
  
- Write "Fixes #XYZ" in the description if this PR fixes Issue #XYZ.

### CODE REVIEW

**Comment by andreamari** [comment]
@andre-a-alves, you made a relevant point:  if we mix cirq, pyquil and qiskit tests in the same files, the commands `make test`
, `make test-qiskit` and `make test-pyquil` lose their original meaning. 

Possible solution: we could rewrite `make test`, `make test-qiskit` and `make test-pyquil` such that test functions are filtered according to keywords ("pyquil", "qiskit", etc.. ) that are present in their names. This should be possible with `pytest -k "keyword"` and `pytest -k "not keyword"` (https://docs.pytest.org/en/latest/example/markers.html#using-k-expr-to-select-tests-based-on-their-name)

About your comment:
>I never got any feedback on my comment about whether we would want to restructure/relocate all tests to take advantage of pyTest's advanced features. Should that be discussed in tomorrow's meeting? Because if we decide that's a good idea, this PR is moot

For the moment, I think we can keep the current structure. If in the future we realize that we really need more advanced test features, we can reconsider the structure.

**Comment by andre-a-alves** [comment]
> @andre-a-alves, you made a relevant point: if we mix cirq, pyquil and qiskit tests in the same files, the commands `make test`
> , `make test-qiskit` and `make test-pyquil` lose their original meaning.
> 
> Possible solution: we could rewrite `make test`, `make test-qiskit` and `make test-pyquil` such that test functions are filtered according to keywords ("pyquil", "qiskit", etc.. ) that are present in their names. This should be possible with `pytest -k "keyword"` and `pytest -k "not keyword"` (https://docs.pytest.org/en/latest/example/markers.html#using-k-expr-to-select-tests-based-on-their-name)

I like that solution. I can start looking into rewriting the makes and looking keywords this evening.

**Comment by rmlarose** [comment]
> @andre-a-alves, you made a relevant point: if we mix cirq, pyquil and qiskit tests in the same files, the commands `make test`
> , `make test-qiskit` and `make test-pyquil` lose their original meaning.

If I may add to this: I personally don't like how many `make test-something` commands we have for unit tests, but I do like a command which is `make test-things-which-aren't-pyquil` because its annoying to have to spin up the quilc and qvm to test this.

It may be outside the scope of this PR, but what about a single `make test` command which

1. Queries whether quilc & qvm are running.
2. Tries to start quilc & qvm if they are not running.
3. Tests everything, skipping pyquil tests if quilc & qvm are not running.

> Possible solution: we could rewrite `make test`, `make test-qiskit` and `make test-pyquil` such that test functions are filtered according to keywords ("pyquil", "qiskit", etc.. ) that are present in their names. This should be possible with `pytest -k "keyword"` and `pytest -k "not keyword"` (https://docs.pytest.org/en/latest/example/markers.html#using-k-expr-to-select-tests-based-on-their-name)

This enforces a new style condition that every pyquil test must have pyquil in the name, which I'm not sure is a good idea. I think I would prefer to isolate all pyquil tests that use qvm and quilc in `mitiq_pyquil`.

**Comment by andre-a-alves** [comment]
As discussed in the meeting
1. PyQuil tests all in mitiq_pyquil/tests
2. Only "make test," "make test-pyquil," and "make test-all" remain
3. Docs updated to relfect

**Review by andreamari — APPROVED** [review]
LGTM!

**Comment by andreamari** [comment]
I re-run the tests to see if the docs problem remains

**Comment by andreamari** [comment]
> I re-run the tests to see if the docs problem remains

Now everything is green apart from a small codecov decrease. I have no idea why but it looks irrelevant to me.

**Pull request merged**
