### PR TITLE
Fixes #489

### LINKED ISSUE #489: Add type check to CI
We had a PR (#326) to add mypy to CI, but while this PR fixed mypy errors it never actually added a job to CI. Do we want to add this?

### PR DESCRIPTION
**Pull request by crazy4pi314**
Description
-----------
 Adds CI typechecks and fixed all current type check issues.

Checklist
-----------
Please make sure you have finished the following tasks before requesting a review of the pull request (PR). For more information, please refer to the [Contributor's Guide](../blob/master/CONTRIBUTING.md):

- [ ] Contributions to mitiq should follow the [pep8 style](https://www.python.org/dev/peps/pep-0008/). You can enforce it easily with [`black`](https://black.readthedocs.io/en/stable/index.html) style and with [`flake8`](http://flake8.pycqa.org) conventions.
- [ ] Please add tests to cover your changes, if applicable, and make sure that all new and existing tests pass locally.
- [ ] If the behavior of the code has changed or new feature has been added, please also [update the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md).
- [ ] Functions and classes have useful [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings and [type hints](https://www.python.org/dev/peps/pep-0484/) in the signature of the objects.
- [ ] (Bug fix) The associated issue is referenced above using [auto-close keywords](https://help.github.com/en/articles/closing-issues-using-keywords). If the PR fixes an issue, use the keyword fix/fixes/fixed followed by the issue id. For example, if the PR fixes issue 1184, type "Fixes #1184" (without quotes).
- [ ] The [changelog](https://github.com/unitaryfund/mitiq/blob/master/CHANGELOG.md) is updated, including author and PR number (@username, gh-xxx).

### CODE REVIEW

**Comment by andreamari** [comment]
@crazy4pi314, maybe we could ignore type checking on test files, if you think this is reasonable.

Actually, I don't know why, but when I run `mypy .` locally it always automatically ignore test files. For some reason `mypy` behaves differently on CI.

**Comment by crazy4pi314** [comment]
> @crazy4pi314, maybe we could ignore type checking on test files, if you think this is reasonable.

I am ok with whatever, I was just running the checks as written in the make file and for me locally and on CI runs `mypy .` at root so it is everything.

> Actually, I don't know why, but when I run `mypy .` locally it always automatically ignore test files. For some reason `mypy` behaves differently on CI.
It could be you have a different local config to mypy, but afaik the config/build in the repo is test all.

**Comment by crazy4pi314** [comment]
This is larger scope than originally intended since type checking has not been done in a while either in source or in the tests (which as @andreamari points out, maybe we don't care there so much). Bumping to next milestone.

**Comment by rmlarose** [comment]
Superseded by #764.

**Pull request closed without merging**
